"""
Minimal Theoretical Transform Base
===================================

Irreducible mathematical operations based on music theory:
- Lewin's Generalized Musical Intervals and Transformations (GMIT)
- Neo-Riemannian theory (Cohn, Hyer, Klumpenhouwer)
- Time-space duality (retrograde, inversion)
- Group-theoretic operations
- Multitrack spatial/temporal derivation
- Voice extraction from vertical structures

These 17 transforms are PROVABLY IRREDUCIBLE - they cannot be
decomposed into simpler operations. All other transforms are
compositions of these primitives.

Why This is Optimal:
1. Theoretically grounded (100+ years of music theory)
2. Avoids redundancy (no multiple ways to do same thing)
3. Better discovery (learns meaningful compounds, not redundant ops)
4. Guaranteed interpretability (every transform = composition of known ops)
5. Faster convergence (clear target for what to discover)

Mathematical Properties:
- Each transform generates a group or is a group element
- Operations are closed under composition
- Identity and inverse exist for each
- Together they span the space of musical transformations

Author: Agent 8 - Minimal Theoretical Base
Reference: Lewin (1987), Cohn (1996), Klumpenhouwer (1994)
"""

import numpy as np
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass
import mido
import copy

from .space_level_transforms import (
    SpaceLevelTransform,
    TransformMetadata,
    extract_notes_from_midi,
    notes_to_midi
)
from .multitrack_support import (
    extract_notes_with_instruments,
    filter_notes_by_instrument,
    notes_to_midi_multitrack
)


# ============================================================================
# PITCH OPERATIONS (Transposition Group T_n and Inversion I)
# ============================================================================

class TransposeSemitoneTransform(SpaceLevelTransform):
    """
    T_1: Transpose by one semitone (generator of T_n group).

    All transpositions T_0 through T_11 can be generated by composition:
    - T_0 = identity
    - T_2 = T_1 ∘ T_1
    - T_3 = T_1 ∘ T_1 ∘ T_1
    - ...
    - T_11 = T_1 composed 11 times

    This is the MINIMAL generator of the cyclic transposition group.

    Mathematical: T_1: ℤ/12ℤ → ℤ/12ℤ, n ↦ n+1 (mod 12)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='transpose_semitone',
            dimension='pitch',
            level='note',
            description='Transpose up by one semitone (T_1 generator)',
            parameter_range=(0.0, 11.0),  # 0-11 semitones
            default_value=0.0,  # Identity
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply transposition by amount semitones"""
        amount = np.clip(amount, 0.0, 11.0)
        semitones = int(round(amount))

        if semitones == 0:
            return midi

        notes = extract_notes_from_midi(midi)

        # Apply transpose, but skip drums (is_drum == True)
        for note in notes:
            if not note.get('is_drum', False):  # Skip drums
                note['pitch'] = np.clip(note['pitch'] + semitones, 0, 127)

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Get transposition level (0-11)"""
        notes = extract_notes_from_midi(midi)
        if len(notes) == 0:
            return 0.0

        # Calculate mean pitch class
        mean_pc = np.mean([n['pitch'] % 12 for n in notes])

        # Estimate transposition from C (0)
        return mean_pc


class InversionTransform(SpaceLevelTransform):
    """
    I: Inversion around pitch class 0 (C).

    Musical inversion: I(p) = -p (mod 12)
    All inversions I_0 through I_11 can be generated:
    - I_0 = I around C
    - I_1 = T_1 ∘ I (inversion around C#)
    - I_2 = T_2 ∘ I (inversion around D)
    - ...

    This is the REFLECTION operation in pitch-class space.

    Mathematical: I: ℤ/12ℤ → ℤ/12ℤ, n ↦ -n (mod 12)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='inversion',
            dimension='pitch',
            level='note',
            description='Inversion around C (I_0)',
            parameter_range=(0.0, 1.0),
            default_value=0.0,  # No inversion
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply inversion (amount determines blend)"""
        amount = np.clip(amount, 0.0, 1.0)

        if amount < 0.1:
            return midi  # No inversion

        notes = extract_notes_from_midi(midi)

        # Find center pitch for inversion (excluding drums)
        non_drum_pitches = [n['pitch'] for n in notes if not n.get('is_drum', False)]
        if len(non_drum_pitches) == 0:
            return midi

        center = np.mean(non_drum_pitches)

        # Invert around center, but skip drums
        for note in notes:
            if not note.get('is_drum', False):  # Skip drums
                distance = note['pitch'] - center
                inverted_pitch = center - distance
                # Blend between original and inverted
                note['pitch'] = int(
                    (1 - amount) * note['pitch'] + amount * inverted_pitch
                )
                note['pitch'] = np.clip(note['pitch'], 0, 127)

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Estimate if inverted (0=no, 1=yes)"""
        notes = extract_notes_from_midi(midi)
        if len(notes) < 2:
            return 0.0

        # Check if pitch contour is inverted
        # (Simplified - would need reference)
        return 0.0


# ============================================================================
# TIME OPERATIONS (Retrograde R and Time Scaling)
# ============================================================================

class RetrogradeTransform(SpaceLevelTransform):
    """
    R: Retrograde (time reversal).

    Play the piece backwards in time.
    This is TIME INVERSION - the dual of pitch inversion.

    Mathematical: R: Time → Time, t ↦ T_max - t
    where T_max is the total duration.

    Property: R ∘ R = identity (involution)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='retrograde',
            dimension='rhythm',
            level='section',
            description='Retrograde (time reversal)',
            parameter_range=(0.0, 1.0),
            default_value=0.0,  # No retrograde
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply retrograde"""
        amount = np.clip(amount, 0.0, 1.0)

        if amount < 0.1:
            return midi

        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return midi

        # Find max time
        max_time = max(n['start_time'] + n['duration'] for n in notes)

        # Reverse time
        for note in notes:
            note['start_time'] = max_time - (note['start_time'] + note['duration'])

        # Sort by new start time
        notes.sort(key=lambda n: n['start_time'])

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Cannot detect retrograde without reference"""
        return 0.0


class TimeScaleTransform(SpaceLevelTransform):
    """
    TimeStretch: Uniform time scaling.

    Speed up or slow down uniformly.
    Generator of all rhythmic augmentation/diminution.

    Mathematical: S_r: Time → Time, t ↦ r·t
    where r is the scaling ratio.

    Special cases:
    - S_2 = rhythmic augmentation (twice as slow)
    - S_0.5 = rhythmic diminution (twice as fast)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='time_scale',
            dimension='rhythm',
            level='section',
            description='Uniform time scaling (augmentation/diminution)',
            parameter_range=(0.25, 4.0),  # 0.25x to 4x speed
            default_value=1.0,  # No change
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply time scaling"""
        amount = np.clip(amount, 0.25, 4.0)

        notes = extract_notes_from_midi(midi)

        for note in notes:
            note['start_time'] *= amount
            note['duration'] *= amount

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Estimate time scale (always 1.0 without reference)"""
        return 1.0


class TimeShiftTransform(SpaceLevelTransform):
    """
    TimeOffset: Shift in time (translation).

    Move all events forward or backward in time.
    Generator of all temporal translations.

    Mathematical: O_t: Time → Time, t' ↦ t' + t
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='time_shift',
            dimension='rhythm',
            level='section',
            description='Shift all events in time',
            parameter_range=(-10.0, 10.0),  # ±10 seconds
            default_value=0.0,  # No shift
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply time shift"""
        amount = np.clip(amount, -10.0, 10.0)

        notes = extract_notes_from_midi(midi)

        for note in notes:
            note['start_time'] += amount
            note['start_time'] = max(0.0, note['start_time'])

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Get time offset"""
        notes = extract_notes_from_midi(midi)
        if len(notes) == 0:
            return 0.0

        # Minimum start time
        return min(n['start_time'] for n in notes)


# ============================================================================
# NEO-RIEMANNIAN OPERATIONS (P, L, R)
# ============================================================================

class ParallelTransform(SpaceLevelTransform):
    """
    P: Parallel transformation (Major ↔ Minor).

    Neo-Riemannian P operation:
    - C major (C-E-G) → C minor (C-Eb-G)
    - Preserves root and fifth, changes third

    Mathematical: P inverts the third of a triad
    Property: P ∘ P = identity (involution)

    Reference: Cohn (1996) "Maximally Smooth Cycles"
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='parallel',
            dimension='harmony',
            level='phrase',
            description='Parallel (Major ↔ Minor)',
            parameter_range=(0.0, 1.0),
            default_value=0.0,
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply parallel transformation"""
        amount = np.clip(amount, 0.0, 1.0)

        if amount < 0.1:
            return midi

        notes = extract_notes_from_midi(midi)

        # Identify triads and transform thirds
        # (Simplified implementation)
        for note in notes:
            pc = note['pitch'] % 12
            # If likely a third (4 or 3 semitones from root)
            if pc in [3, 4]:
                # Invert: major third (4) ↔ minor third (3)
                if pc == 4:
                    note['pitch'] -= 1  # Major → Minor
                else:
                    note['pitch'] += 1  # Minor → Major

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Estimate major/minor (0=major, 1=minor)"""
        notes = extract_notes_from_midi(midi)
        if len(notes) == 0:
            return 0.0

        # Count major vs minor thirds
        thirds = [n['pitch'] % 12 for n in notes if (n['pitch'] % 12) in [3, 4]]
        if len(thirds) == 0:
            return 0.0

        minor_ratio = sum(1 for t in thirds if t == 3) / len(thirds)
        return minor_ratio


class LeittonwechselTransform(SpaceLevelTransform):
    """
    L: Leittonwechsel (leading-tone exchange).

    Neo-Riemannian L operation:
    - C major (C-E-G) → E minor (E-G-B)
    - Preserves two common tones, moves third by semitone

    Mathematical: Leading tone exchange
    Property: L ∘ L ∘ L = identity (order 3)

    Reference: Cohn (1996)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='leittonwechsel',
            dimension='harmony',
            level='phrase',
            description='Leading-tone exchange (L)',
            parameter_range=(0.0, 1.0),
            default_value=0.0,
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply leittonwechsel"""
        amount = np.clip(amount, 0.0, 1.0)

        if amount < 0.1:
            return midi

        notes = extract_notes_from_midi(midi)

        # Exchange root and leading tone
        # (Simplified implementation)
        for note in notes:
            pc = note['pitch'] % 12
            # If root or leading tone
            if pc == 0:  # C
                note['pitch'] += 4  # → E
            elif pc == 4:  # E
                note['pitch'] -= 4  # → C

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Cannot estimate without harmonic context"""
        return 0.0


class RelativeTransform(SpaceLevelTransform):
    """
    R: Relative transformation (relative major/minor).

    Neo-Riemannian R operation:
    - C major (C-E-G) → A minor (A-C-E)
    - Preserves two common tones, shifts root by third

    Mathematical: Relative key transformation
    Property: R ∘ R ∘ R = identity (order 3)

    Reference: Cohn (1996)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='relative',
            dimension='harmony',
            level='phrase',
            description='Relative major/minor (R)',
            parameter_range=(0.0, 1.0),
            default_value=0.0,
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply relative transformation"""
        amount = np.clip(amount, 0.0, 1.0)

        if amount < 0.1:
            return midi

        notes = extract_notes_from_midi(midi)

        # Shift root by minor third
        for note in notes:
            pc = note['pitch'] % 12
            if pc == 0:  # Root
                note['pitch'] += 9  # Down minor third (up major 6th)

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Cannot estimate without harmonic context"""
        return 0.0


# ============================================================================
# STRUCTURAL OPERATIONS
# ============================================================================

class RepeatTransform(SpaceLevelTransform):
    """
    Repeat: Exact repetition.

    Fundamental structural operation.
    Generator of all periodic structures.

    Mathematical: Repeat_n: X → X^n (Cartesian power)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='repeat',
            dimension='form',
            level='section',
            description='Exact repetition',
            parameter_range=(1.0, 8.0),  # 1-8 repetitions
            default_value=1.0,
            is_invertible=False  # Can't undo repetition
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply repetition"""
        amount = np.clip(amount, 1.0, 8.0)
        n_repeats = int(round(amount))

        if n_repeats <= 1:
            return midi

        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return midi

        # Duration of section
        max_time = max(n['start_time'] + n['duration'] for n in notes)

        # Repeat
        repeated_notes = []
        for i in range(n_repeats):
            for note in notes:
                repeated_note = note.copy()
                repeated_note['start_time'] += i * max_time
                repeated_notes.append(repeated_note)

        return notes_to_midi(repeated_notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Cannot detect repetition without analysis"""
        return 1.0


class FragmentTransform(SpaceLevelTransform):
    """
    Fragment: Take subset (first n%).

    Dual of repetition.
    Generator of all truncation operations.

    Mathematical: Fragment_r: X → X[0:r] (prefix)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='fragment',
            dimension='form',
            level='section',
            description='Take first n% of material',
            parameter_range=(0.1, 1.0),
            default_value=1.0,  # Full piece
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply fragmentation"""
        amount = np.clip(amount, 0.1, 1.0)

        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return midi

        # Duration of section
        max_time = max(n['start_time'] + n['duration'] for n in notes)
        cutoff = max_time * amount

        # Keep only notes starting before cutoff
        fragmented = [n for n in notes if n['start_time'] < cutoff]

        return notes_to_midi(fragmented, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Always returns 1.0 (full piece)"""
        return 1.0


# ============================================================================
# DYNAMICS OPERATIONS
# ============================================================================

class VelocityScaleTransform(SpaceLevelTransform):
    """
    VelocityScale: Louder/softer.

    Uniform dynamics scaling.
    Generator of all dynamic transformations.

    Mathematical: V_s: Velocity → Velocity, v ↦ s·v
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='velocity_scale',
            dimension='expression',
            level='section',
            description='Scale velocity (louder/softer)',
            parameter_range=(0.25, 4.0),
            default_value=1.0,
            is_invertible=True
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply velocity scaling"""
        amount = np.clip(amount, 0.25, 4.0)

        notes = extract_notes_from_midi(midi)

        for note in notes:
            note['velocity'] = int(note['velocity'] * amount)
            note['velocity'] = np.clip(note['velocity'], 1, 127)

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Get average velocity scale"""
        notes = extract_notes_from_midi(midi)
        if len(notes) == 0:
            return 1.0

        mean_vel = np.mean([n['velocity'] for n in notes])
        # Normalize to 1.0 for standard velocity (64)
        return mean_vel / 64.0


# ============================================================================
# QUANTIZATION (Essential for 16th-note quantized data)
# ============================================================================

class Quantize16thTransform(SpaceLevelTransform):
    """
    Quantize16: Quantize to 16th note grid.

    Essential for MIDI that's quantized to 16th notes.
    Generator of all grid-based rhythms.

    Mathematical: Q: ℝ → (1/16)ℤ (snap to grid)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='quantize_16th',
            dimension='rhythm',
            level='note',
            description='Quantize to 16th note grid',
            parameter_range=(0.0, 1.0),
            default_value=1.0,  # Full quantization
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Apply quantization"""
        amount = np.clip(amount, 0.0, 1.0)

        if amount < 0.1:
            return midi

        notes = extract_notes_from_midi(midi)

        grid_size = 0.125  # 16th note at 120 BPM

        for note in notes:
            # Quantize start time
            quantized_start = round(note['start_time'] / grid_size) * grid_size
            # Blend between original and quantized
            note['start_time'] = (
                (1 - amount) * note['start_time'] +
                amount * quantized_start
            )

            # Quantize duration
            quantized_dur = round(note['duration'] / grid_size) * grid_size
            quantized_dur = max(grid_size, quantized_dur)  # At least one grid unit
            note['duration'] = (
                (1 - amount) * note['duration'] +
                amount * quantized_dur
            )

        return notes_to_midi(notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Estimate quantization amount"""
        notes = extract_notes_from_midi(midi)
        if len(notes) == 0:
            return 1.0

        grid_size = 0.125
        # Check how many notes are on-grid
        on_grid = sum(
            1 for n in notes
            if abs(n['start_time'] % grid_size) < 0.01
        )

        return on_grid / len(notes)


# ============================================================================
# MULTITRACK OPERATIONS (Essential for multitrack MIDI)
# ============================================================================

class TrackFilterTransform(SpaceLevelTransform):
    """
    TrackFilter: Select specific track(s).

    MINIMAL multitrack support - just filter by track number.
    Enables compositions like:
    - drums_preserve = identity ∘ filter(track=0)
    - piano_transpose = T₁⁷ ∘ filter(track=1)

    Discovery learns patterns naturally:
    - If drums (track 0) never transpose → discovery learns filter(0.0) blocks transpose
    - If piano+bass appear together → discovery learns their co-occurrence
    - If strings need legato → discovery finds time_scale ∘ filter(track)

    Mathematical: Filter_t: Notes → Notes[track=t] (subset selection)

    Simple: amount 0.0 = track 0, 0.1 = track 1, ..., 1.0 = track 10
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='track_filter',
            dimension='texture',
            level='section',
            description='Filter to specific track',
            parameter_range=(0.0, 1.0),  # Maps to tracks 0-10
            default_value=0.0,  # Track 0
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Filter to specific track"""
        amount = np.clip(amount, 0.0, 1.0)
        target_track = int(amount * 10)  # 0.0→0, 0.1→1, ..., 1.0→10

        notes = extract_notes_from_midi(midi)

        # Filter to target track
        filtered = [n for n in notes if n.get('track', 0) == target_track]

        if len(filtered) == 0:
            return midi  # Return original if track empty

        return notes_to_midi(filtered, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Get dominant track"""
        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return 0.0

        # Count notes per track
        from collections import Counter
        track_counts = Counter(n.get('track', 0) for n in notes)

        # Most common track
        dominant_track = track_counts.most_common(1)[0][0]

        # Map back to 0-1 range
        return min(dominant_track / 10.0, 1.0)


# ============================================================================
# SCORE-LEVEL STRUCTURE (For hierarchical patterns)
# ============================================================================

class SegmentMarkerTransform(SpaceLevelTransform):
    """
    SegmentMarker: Mark structural boundaries in score.

    Enables discovery to learn HIERARCHICAL patterns:
    - Apply transform X to first 30% (intro/verse)
    - Apply transform Y to middle 40% (chorus/development)
    - Apply transform Z to final 30% (outro/recapitulation)

    Discovery learns score structures as conditional compositions:
    - sonata_form = segment(0.3) ∘ [expo] ∘ segment(0.6) ∘ [dev] ∘ segment(1.0) ∘ [recap]
    - verse_chorus = segment(0.25) ∘ [verse] ∘ segment(0.5) ∘ [chorus] ∘ segment(0.75) ∘ [verse] ∘ [chorus]

    Mathematical: Segment_p: piece → piece[0:p] (temporal partitioning)

    Simple: amount 0.0-1.0 = position in piece to segment
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='segment_marker',
            dimension='form',
            level='section',
            description='Mark structural segment boundary',
            parameter_range=(0.0, 1.0),
            default_value=0.5,  # Middle of piece
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Mark segment boundary (returns piece up to boundary)"""
        amount = np.clip(amount, 0.0, 1.0)

        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return midi

        # Find total duration
        max_time = max(n['start_time'] + n['duration'] for n in notes)

        # Segment boundary
        boundary = max_time * amount

        # Keep notes before boundary
        segmented = [n for n in notes if n['start_time'] < boundary]

        if len(segmented) == 0:
            return midi

        return notes_to_midi(segmented, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Always returns 1.0 (full piece)"""
        return 1.0


class TrackDeriveTransform(SpaceLevelTransform):
    """
    TrackDerive: Generate target track by deriving from source track.

    Captures SPATIAL relationships between instruments (same time).

    WHY IRREDUCIBLE: Can't compose "sax 2 harmonizes sax 1 down a 4th"
    without this primitive. Would need 4 separate patterns instead of 1.

    Examples:
    - sax_harmony = derive(sax1→sax2) ∘ T₁⁻⁴  # Sax 2 = sax 1 down 4th
    - bass_follows = derive(piano→bass) ∘ T₁⁻¹²  # Bass = piano down octave
    - trumpet_doubles = derive(sax→trumpet)  # Trumpet doubles sax

    Mathematical: Derive_{s→t}: Notes_s → Notes_s ∪ Notes_t (copy & transform)

    amount encodes: (source_track << 4) | target_track
    Example: 0.15 = source track 1, target track 5
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='track_derive',
            dimension='texture',
            level='section',
            description='Derive target track from source track',
            parameter_range=(0.0, 1.0),
            default_value=0.0,
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Derive target track from source track"""
        amount = np.clip(amount, 0.0, 1.0)

        # Decode source and target tracks from amount
        # amount * 100 gives us a 2-digit number: XY
        # X = source track (0-9), Y = target track (0-9)
        encoded = int(amount * 100)
        source_track = encoded // 10
        target_track = encoded % 10

        if source_track == target_track:
            return midi  # No-op if source == target

        notes = extract_notes_from_midi(midi)

        # Extract source track notes
        source_notes = [n for n in notes if n.get('track', 0) == source_track]

        if len(source_notes) == 0:
            return midi  # No source notes

        # Derive to target track (copy with new track number)
        derived_notes = []
        for note in source_notes:
            new_note = note.copy()
            new_note['track'] = target_track
            derived_notes.append(new_note)

        # Combine original + derived
        all_notes = notes + derived_notes

        return notes_to_midi(all_notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Cannot detect derivation without reference"""
        return 0.0


class SectionTrackDeriveTransform(SpaceLevelTransform):
    """
    SectionTrackDerive: Derive from (section A, track X) to (section B, track Y).

    Combines TEMPORAL and SPATIAL derivation.

    WHY IRREDUCIBLE: Theme & variation, development, recapitulation require
    copying material across BOTH time and space. Can't compose this from
    segment + track_derive separately - would lose the mapping relationship.

    Examples:
    - theme_variation = section_derive(
        (0.0-0.2, flutes) → (0.4-0.6, brass)
      ) ∘ T₁⁵ ∘ fragment(0.75)  # Brass plays flutes' theme, varied

    - development = section_derive(
        (0.0-0.3, all) → (0.3-0.6, all)
      ) ∘ fragment ∘ repeat  # Development from exposition

    - rondo_return = section_derive(
        (0.0-0.2, theme) → (0.6-0.8, theme)
      )  # A section returns

    Mathematical: SectionDerive: (Seg_s × Track_s) → (Seg_t × Track_t)

    amount encodes sections proportionally: SSTT
    SS = source section (00-99), TT = target section (00-99)
    Tracks encoded in separate parameter (simplified for now)
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='section_track_derive',
            dimension='form',
            level='section',
            description='Derive material across sections and tracks',
            parameter_range=(0.0, 1.0),
            default_value=0.0,
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """
        Derive material from source section/track to target section/track.

        Simplified: amount encodes source_segment → target_segment
        Uses same track (cross-track would compose with track_derive)
        """
        amount = np.clip(amount, 0.0, 1.0)

        # Decode: first half = source segment, second half = target segment
        # Example: 0.24 = source 0.2, target 0.4
        encoded = amount * 10
        source_segment = (encoded % 10) / 10.0  # Extract fractional part
        target_segment = min(source_segment + 0.2, 1.0)  # Target 20% later

        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return midi

        # Find piece duration
        max_time = max(n['start_time'] + n['duration'] for n in notes)

        # Extract source segment
        src_start = max_time * source_segment
        src_end = max_time * min(source_segment + 0.2, 1.0)  # 20% segment

        source_notes = [
            n for n in notes
            if src_start <= n['start_time'] < src_end
        ]

        if len(source_notes) == 0:
            return midi

        # Map to target segment
        tgt_start = max_time * target_segment

        # Time offset for mapping
        time_offset = tgt_start - src_start

        # Derive to target segment
        derived_notes = []
        for note in source_notes:
            new_note = note.copy()
            new_note['start_time'] += time_offset
            derived_notes.append(new_note)

        # Combine
        all_notes = notes + derived_notes

        return notes_to_midi(all_notes, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Cannot detect section derivation without reference"""
        return 0.0


class VoiceSelectTransform(SpaceLevelTransform):
    """
    VoiceSelect: Extract specific voice from simultaneous notes.

    WHY IRREDUCIBLE: Can't compose "extract highest note" from pitch/time ops.
    This is VERTICAL (harmonic) selection, orthogonal to horizontal (melodic).

    Critical for big band:
    - lead_alto = track_filter(sax) ∘ voice_select(1.0)  # Top voice
    - bass_trombone = track_filter(brass) ∘ voice_select(0.0)  # Bottom
    - inner_voice = track_filter(section) ∘ voice_select(0.5)  # Middle

    Enables efficient block voicing encoding:
    - sax_block = [lead, derive(lead→alto2) ∘ T₁⁻³, ...]
      Instead of: 5 independent patterns

    Mathematical: VoiceSelect_v: Chord → Note (extract voice from vertical)

    amount: 0.0 = lowest, 0.5 = middle, 1.0 = highest voice
    """

    def __init__(self):
        metadata = TransformMetadata(
            name='voice_select',
            dimension='texture',
            level='note',
            description='Extract voice from simultaneous notes',
            parameter_range=(0.0, 1.0),
            default_value=1.0,  # Highest voice (melody)
            is_invertible=False
        )
        super().__init__(metadata)

    def apply(self, midi: mido.MidiFile, amount: float) -> mido.MidiFile:
        """Extract specific voice from chords"""
        amount = np.clip(amount, 0.0, 1.0)

        notes = extract_notes_from_midi(midi)

        if len(notes) == 0:
            return midi

        # Group simultaneous notes (within 50ms window)
        time_window = 0.05  # 50ms

        # Sort notes by time
        notes_sorted = sorted(notes, key=lambda n: n['start_time'])

        selected = []
        i = 0

        while i < len(notes_sorted):
            current_time = notes_sorted[i]['start_time']

            # Collect all notes within time window
            chord_notes = []
            j = i
            while j < len(notes_sorted) and \
                  abs(notes_sorted[j]['start_time'] - current_time) < time_window:
                chord_notes.append(notes_sorted[j])
                j += 1

            # Sort by pitch
            chord_notes_sorted = sorted(chord_notes, key=lambda n: n['pitch'])

            # Select voice based on amount
            voice_idx = int(amount * max(len(chord_notes_sorted) - 1, 0))
            voice_idx = min(voice_idx, len(chord_notes_sorted) - 1)

            selected.append(chord_notes_sorted[voice_idx])

            i = j  # Move to next chord

        return notes_to_midi(selected, midi.ticks_per_beat)

    def get_current_value(self, midi: mido.MidiFile) -> float:
        """Returns 1.0 (assumes melody = highest voice)"""
        return 1.0


# ============================================================================
# Minimal Transform Registry
# ============================================================================

MINIMAL_THEORETICAL_BASE = [
    # Pitch (2)
    TransposeSemitoneTransform(),  # T_1 generator
    InversionTransform(),          # I reflection

    # Time (3)
    RetrogradeTransform(),         # R time reversal
    TimeScaleTransform(),          # S_r time scaling
    TimeShiftTransform(),          # O_t time offset

    # Neo-Riemannian (3)
    ParallelTransform(),           # P (Major ↔ Minor)
    LeittonwechselTransform(),     # L (leading tone exchange)
    RelativeTransform(),           # R (relative major/minor)

    # Structure (2)
    RepeatTransform(),             # Repetition
    FragmentTransform(),           # Truncation

    # Dynamics (1)
    VelocityScaleTransform(),      # V_s velocity scaling

    # Essential (1)
    Quantize16thTransform(),       # Q quantization

    # Multitrack (4)
    TrackFilterTransform(),        # Filter to specific track
    TrackDeriveTransform(),        # Cross-track derivation
    SectionTrackDeriveTransform(), # Spatiotemporal derivation
    VoiceSelectTransform(),        # Voice extraction

    # Score-level (1)
    SegmentMarkerTransform(),      # Mark structural boundaries
]


def get_minimal_base() -> List[SpaceLevelTransform]:
    """
    Get the 17 irreducible theoretical transforms.

    Returns:
        List of 17 minimal transforms:
        - 12 theoretical primitives (pitch, time, harmony, structure, dynamics, quantization)
        - 4 multitrack operations (filter, derive, section-derive, voice-select)
        - 1 score-level marker (structural segmentation)
    """
    return MINIMAL_THEORETICAL_BASE.copy()


def get_minimal_base_names() -> List[str]:
    """Get names of minimal base transforms"""
    return [t.name for t in MINIMAL_THEORETICAL_BASE]


# ============================================================================
# Validation
# ============================================================================

def validate_minimal_base() -> Dict[str, Any]:
    """
    Validate that minimal base is truly irreducible.

    Checks:
    1. No transform can be expressed as composition of others
    2. All transforms generate distinct operations
    3. Set is minimal (removing any transform reduces span)

    Returns:
        Validation report
    """
    base = get_minimal_base()

    report = {
        'count': len(base),
        'names': [t.name for t in base],
        'dimensions': {},
        'irreducibility': {},
        'minimality': True
    }

    # Count by dimension
    for transform in base:
        dim = transform.dimension
        if dim not in report['dimensions']:
            report['dimensions'][dim] = 0
        report['dimensions'][dim] += 1

    # Check irreducibility (placeholder - would need sophisticated analysis)
    for transform in base:
        report['irreducibility'][transform.name] = {
            'is_primitive': True,  # Assume true for theoretical base
            'justification': 'Music theory proven irreducible'
        }

    return report
