#!/usr/bin/env bash
# Pull src/ + public/ from ../var/www/html/doseedo-react (CRA source of truth)
# and re-apply the Next.js-specific transforms. Idempotent — safe to re-run.
#
# Source of truth: /Users/hydroadmin/Downloads/Do/var/www/html/doseedo-react/
# Runs automatically before `npm run dev` and `npm run build` (see package.json).

set -euo pipefail

SRC_ROOT="$(cd "$(dirname "$0")/.." && pwd)/var/www/html/doseedo-react"
DST_ROOT="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -d "$SRC_ROOT/src" ]]; then
  echo "sync.sh: source tree not found at $SRC_ROOT/src" >&2
  exit 1
fi

echo "sync.sh: pulling from $SRC_ROOT"

# 1. rsync src/ — delete stale files so removals in CRA propagate
rsync -a --delete --exclude='.DS_Store' "$SRC_ROOT/src/" "$DST_ROOT/src/"

# 2. rsync public/ — but keep root index.html & home/ out (CRA-specific auth gate
#    is already ported into app/layout.tsx; /home is served via Next rewrite).
rsync -a --delete \
  --exclude='.DS_Store' \
  --exclude='index.html' \
  --exclude='home/' \
  "$SRC_ROOT/public/" "$DST_ROOT/public/"

# 3. REACT_APP_ → NEXT_PUBLIC_ (idempotent — no-op if already renamed)
find "$DST_ROOT/src" -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' \) \
  -exec grep -l 'REACT_APP_' {} + 2>/dev/null | while read -r f; do
  LC_ALL=C sed -i '' 's/REACT_APP_/NEXT_PUBLIC_/g' "$f"
done

# 4. Rename shader-utils.js → .ts (files contain TS interface declarations
#    that CRA tolerates but Next's TS check rejects). Idempotent.
for d in "$DST_ROOT/src/components/GlassCard" "$DST_ROOT/src/components-demo/GlassCard"; do
  if [[ -f "$d/shader-utils.js" && ! -f "$d/shader-utils.ts" ]]; then
    mv "$d/shader-utils.js" "$d/shader-utils.ts"
  elif [[ -f "$d/shader-utils.js" && -f "$d/shader-utils.ts" ]]; then
    # rsync brought back the .js; the .ts is our canonical version
    rm "$d/shader-utils.js"
  fi
done

# 5. Extract top-level :root { ... } blocks from .module.css files into a
#    single global stylesheet (Next CSS Modules forbid non-pure selectors).
mkdir -p "$DST_ROOT/src/styles"
OUT_ROOT="$DST_ROOT/src/styles/module-extracted-root.css"
{
  echo "/* AUTO-GENERATED by sync.sh. Edit sync.sh, not this file. */"
  echo "/* :root blocks extracted from *.module.css — imported globally in app/AppShell.tsx. */"
  echo ""
} > "$OUT_ROOT"

while IFS= read -r f; do
  # Top-level :root { ... } — append to global
  awk '
    /^:root \{$/        { c=1; print; next }
    c && /^\}$/         { print; c=0; next }
    c                   { print }
  ' "$f" >> "$OUT_ROOT"
  echo "" >> "$OUT_ROOT"

  # Strip top-level :root { ... } from the module (leave @media { :root } alone for step 6)
  awk '
    /^:root \{$/        { s=1; next }
    s && /^\}$/         { s=0; next }
    !s                  { print }
  ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done < <(grep -rl '^:root {$' "$DST_ROOT/src" --include='*.module.css' 2>/dev/null || true)

# 5b. Extract the nested @media{:root{...}} override in DAW.module.css
for f in "$DST_ROOT/src/components/DAW/DAW.module.css" \
         "$DST_ROOT/src/components-demo/DAW/DAW.module.css"; do
  [[ -f "$f" ]] || continue
  # If the nested rule is present (indented 2 spaces under a @media), strip it;
  # we append an equivalent global rule below.
  if grep -q '^  :root {$' "$f"; then
    awk '
      /^  :root \{$/      { s=1; next }
      s && /^  \}$/       { s=0; next }
      !s                  { print }
    ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
  fi
done
# Append responsive :root override (once)
if ! grep -q 'Responsive :root override' "$OUT_ROOT"; then
  cat >> "$OUT_ROOT" <<'EOF'

/* Responsive :root override (was nested under @media in DAW.module.css) */
@media (max-width: 819.2px) {
  :root {
    --bus-label-width: 160px;
  }
}
EOF
fi

# 6. Extract pure-:global() rules from .module.css — bare :global(.third-party)
#    blocks without a trailing local class fail Next's purity check.
OUT_GLOBAL="$DST_ROOT/src/styles/module-extracted-global.css"
{
  echo "/* AUTO-GENERATED by sync.sh. Edit sync.sh, not this file. */"
  echo "/* Pure :global() blocks extracted from *.module.css (third-party CSS overrides). */"
  echo ""
} > "$OUT_GLOBAL"

while IFS= read -r f; do
  awk -v out="$OUT_GLOBAL" '
    $0 ~ /^:global\([^)]+\)[[:space:]]*\{[[:space:]]*$/ { c=1; print $0 >> out; next }
    c && /^\}/ { print $0 >> out; print "" >> out; c=0; next }
    c { print $0 >> out }
  ' "$f"
  awk '
    $0 ~ /^:global\([^)]+\)[[:space:]]*\{[[:space:]]*$/ && s==0 { s=1; next }
    s==1 { if ($0 ~ /^\}/) { s=0; next } next }
    { print }
  ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done < <(grep -rlE '^:global\([^)]+\)[[:space:]]*\{[[:space:]]*$' "$DST_ROOT/src" --include='*.module.css' 2>/dev/null || true)

# Strip :global(...) wrappers in the global file (bare selectors outside modules)
LC_ALL=C sed -i '' -E 's/:global\(([^)]+)\)/\1/g' "$OUT_GLOBAL"

echo "sync.sh: done."
echo "  src files : $(find "$DST_ROOT/src" -type f | wc -l | tr -d ' ')"
echo "  public    : $(find "$DST_ROOT/public" -type f | wc -l | tr -d ' ')"
echo "  extracted : root=$(wc -l <"$OUT_ROOT" | tr -d ' ')L  global=$(wc -l <"$OUT_GLOBAL" | tr -d ' ')L"
