/**
 * Plugin Templates — pre-built starter configs with auto-bound UI + DSP
 */

export const PLUGIN_TEMPLATES = [
  // ── 1. Analog Compressor (LA-2A style) ─────────────────────────────────
  {
    name: 'Analog Compressor',
    icon: 'fa-gauge-high',
    color: '#d4a574',
    description: 'Vintage optical leveling amplifier',
    pluginConfig: {
      name: 'Vintage Leveler',
      width: 704,
      height: 330,
      bgColor: '#c8c0b4',
      titleBarColor: '#b8b0a4',
    },
    components: [
      { type: 'panel', x: 4, y: 4, width: 696, height: 322, bgColor: 'rgba(200,192,180,0.6)', borderColor: '#a09888', borderRadius: 3, label: '', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.3), inset 0 -1px 0 rgba(0,0,0,0.1)' },
      { type: 'label', x: 172, y: 10, width: 360, height: 28, label: 'VINTAGE LEVELER', color: '#3a3530', fontSize: 18, fontWeight: 700, letterSpacing: '0.15em', textAlign: 'center' },
      { type: 'meter', x: 202, y: 42, width: 300, height: 155, color: '#3a3530', label: 'GAIN REDUCTION', svgStyle: 'vu-needle', bodyColor: '#f5f0e8', indicatorColor: '#2a2520', accentColor: '#8b0000' },
      { type: 'label', x: 68, y: 202, width: 160, height: 18, label: 'THRESHOLD', color: '#3a3530', fontSize: 11, fontWeight: 600, letterSpacing: '0.1em', textAlign: 'center' },
      { type: 'knob', x: 98, y: 220, width: 100, height: 100, color: '#e2c499', label: '', svgStyle: 'flux', fluxPrompt: 'vintage 1960s dark brown bakelite compressor knob with flat pointer tab indicator, industrial audio hardware, worn aged patina, top-down view, black background' },
      { type: 'label', x: 476, y: 202, width: 160, height: 18, label: 'MAKEUP', color: '#3a3530', fontSize: 11, fontWeight: 600, letterSpacing: '0.1em', textAlign: 'center' },
      { type: 'knob', x: 506, y: 220, width: 100, height: 100, color: '#e2c499', label: '', svgStyle: 'flux', fluxPrompt: 'vintage 1960s dark brown bakelite compressor knob with flat pointer tab indicator, industrial audio hardware, worn aged patina, top-down view, black background' },
      { type: 'label', x: 292, y: 208, width: 120, height: 16, label: 'LIMIT / COMPRESS', color: '#3a3530', fontSize: 9, fontWeight: 600, letterSpacing: '0.08em', textAlign: 'center' },
      { type: 'button', x: 317, y: 230, width: 70, height: 50, color: '#e2c499', label: '', svgStyle: 'vintage-toggle', bodyColor: '#afafaa', indicatorColor: '#e2c499', accentColor: '#a6947a' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Vintage Leveler',
      parameters: [
        { id: 'threshold', name: 'Threshold', min: -60, max: 0, default: -18, unit: 'dB' },
        { id: 'makeup', name: 'Makeup', min: 0, max: 40, default: 0, unit: 'dB' },
        { id: 'mode', name: 'Limit/Compress', min: 0, max: 1, default: 0 },
      ],
      dspChain: [
        { type: 'compressor', id: 'optical_comp', params: { threshold: '@threshold', ratio: '(@mode ? 10 : 4)', attack: 0.01, release: 0.3 } },
        { type: 'saturation', id: 'tube_sat', params: { drive: 1.3, mix: 0.12 } },
        { type: 'gain', id: 'output_gain', params: { gain_db: '@makeup' } },
      ],
      routing: { input: 'stereo', chain: ['optical_comp', 'tube_sat', 'output_gain'], output: 'stereo' },
    },
  },

  // ── 2. Tape Delay ──────────────────────────────────────────────────────
  {
    name: 'Tape Delay',
    icon: 'fa-compact-disc',
    color: '#7b9cc9',
    description: 'Glassmorphic tape echo',
    pluginConfig: {
      name: 'Echo Tape',
      width: 580,
      height: 360,
      bgColor: '#0f1628',
      titleBarColor: '#1a2540',
    },
    components: [
      { type: 'panel', x: 20, y: 20, width: 540, height: 320, bgColor: 'rgba(123,156,201,0.03)', borderColor: 'rgba(123,156,201,0.1)', backdropBlur: 12, borderRadius: 16, label: '' },
      { type: 'label', x: 40, y: 30, width: 180, height: 26, label: 'ECHO TAPE', color: '#7b9cc9', fontSize: 17 },
      { type: 'waveform', x: 200, y: 24, width: 340, height: 40, color: '#7b9cc9', label: '' },
      { type: 'knob', x: 40, y: 80, width: 75, height: 85, color: '#7b9cc9', label: 'Time' },
      { type: 'knob', x: 140, y: 80, width: 75, height: 85, color: '#7b9cc9', label: 'Feedback' },
      { type: 'knob', x: 240, y: 80, width: 75, height: 85, color: '#5a7faa', label: 'Tone' },
      { type: 'knob', x: 340, y: 80, width: 75, height: 85, color: '#5a7faa', label: 'Wow' },
      { type: 'knob', x: 440, y: 80, width: 75, height: 85, color: '#5a7faa', label: 'Flutter' },
      { type: 'knob', x: 90, y: 210, width: 75, height: 85, color: '#94b8de', label: 'Width' },
      { type: 'knob', x: 240, y: 210, width: 75, height: 85, color: '#94b8de', label: 'Mix' },
      { type: 'button', x: 400, y: 240, width: 80, height: 32, color: '#7b9cc9', label: 'Ping Pong' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Echo Tape',
      parameters: [
        { id: 'time', name: 'Time', min: 10, max: 1500, default: 375, skew: 0.4, unit: 'ms' },
        { id: 'feedback', name: 'Feedback', min: 0, max: 95, default: 45, unit: '%' },
        { id: 'tone', name: 'Tone', min: 200, max: 12000, default: 4000, skew: 0.25, unit: 'Hz' },
        { id: 'wow', name: 'Wow', min: 0, max: 100, default: 25, unit: '%' },
        { id: 'flutter', name: 'Flutter', min: 0, max: 100, default: 30, unit: '%' },
        { id: 'width', name: 'Width', min: 0, max: 100, default: 60, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 35, unit: '%' },
      ],
      dspChain: [
        { type: 'ping_pong_delay', id: 'delay1', params: { time: '@time', feedback: '@feedback' } },
        { type: 'lowpass', id: 'tone1', params: { frequency: '@tone', q: 0.7 } },
        { type: 'lfo', id: 'wow1', params: { rate: 0.5, depth: '@wow', shape: 'sine' } },
        { type: 'lfo', id: 'flutter1', params: { rate: 6.0, depth: '@flutter', shape: 'sine' } },
        { type: 'saturation', id: 'tape_sat', params: { drive: 1.5, mix: 0.2 } },
        { type: 'pan', id: 'width1', params: { width: '@width' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['delay1', 'tone1', 'wow1', 'flutter1', 'tape_sat', 'width1', 'mix1'], output: 'stereo' },
    },
  },

  // ── 3. Subtractive Synth ───────────────────────────────────────────────
  {
    name: 'Subtractive Synth',
    icon: 'fa-wave-square',
    color: '#e06c9f',
    description: 'Classic oscillator + filter + envelope',
    pluginConfig: {
      name: 'Pink Pulse',
      width: 650,
      height: 420,
      bgColor: '#1a0f18',
      titleBarColor: '#2d1828',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 200, height: 195, bgColor: 'rgba(224,108,159,0.04)', borderColor: 'rgba(224,108,159,0.12)', borderRadius: 10, label: 'OSC' },
      { type: 'dropdown', x: 30, y: 40, width: 100, height: 26, color: '#e06c9f', label: 'Waveform' },
      { type: 'knob', x: 30, y: 80, width: 65, height: 75, color: '#e06c9f', label: 'Tune' },
      { type: 'knob', x: 120, y: 80, width: 65, height: 75, color: '#e06c9f', label: 'Detune' },
      { type: 'panel', x: 225, y: 15, width: 200, height: 195, bgColor: 'rgba(180,80,140,0.04)', borderColor: 'rgba(180,80,140,0.12)', borderRadius: 10, label: 'FILTER' },
      { type: 'knob', x: 240, y: 50, width: 75, height: 85, color: '#b4508c', label: 'Cutoff' },
      { type: 'knob', x: 340, y: 50, width: 75, height: 85, color: '#b4508c', label: 'Resonance' },
      { type: 'knob', x: 290, y: 150, width: 55, height: 65, color: '#8a3d6e', label: 'Env Amt' },
      { type: 'panel', x: 435, y: 15, width: 200, height: 195, bgColor: 'rgba(224,108,159,0.04)', borderColor: 'rgba(224,108,159,0.12)', borderRadius: 10, label: 'AMP' },
      { type: 'knob', x: 455, y: 50, width: 55, height: 65, color: '#c96090', label: 'Attack' },
      { type: 'knob', x: 525, y: 50, width: 55, height: 65, color: '#c96090', label: 'Decay' },
      { type: 'knob', x: 455, y: 130, width: 55, height: 65, color: '#c96090', label: 'Sustain' },
      { type: 'knob', x: 525, y: 130, width: 55, height: 65, color: '#c96090', label: 'Release' },
      { type: 'panel', x: 15, y: 220, width: 620, height: 185, bgColor: 'rgba(224,108,159,0.03)', borderColor: 'rgba(224,108,159,0.08)', borderRadius: 10, label: 'OUTPUT' },
      { type: 'knob', x: 40, y: 260, width: 70, height: 80, color: '#e06c9f', label: 'Volume' },
      { type: 'knob', x: 140, y: 260, width: 70, height: 80, color: '#94506e', label: 'Glide' },
      { type: 'waveform', x: 260, y: 260, width: 200, height: 50, color: '#e06c9f', label: '' },
      { type: 'meter', x: 500, y: 250, width: 24, height: 120, color: '#e06c9f', label: 'Out' },
    ],
    dspConfig: {
      pluginType: 'instrument',
      name: 'Pink Pulse',
      midi: { voices: 8, pitchBendRange: 2 },
      parameters: [
        { id: 'tune', name: 'Tune', min: -24, max: 24, default: 0, unit: 'st' },
        { id: 'detune', name: 'Detune', min: -50, max: 50, default: 0, unit: 'ct' },
        { id: 'cutoff', name: 'Cutoff', min: 20, max: 20000, default: 8000, skew: 0.25, unit: 'Hz' },
        { id: 'resonance', name: 'Resonance', min: 0, max: 100, default: 20, unit: '%' },
        { id: 'env_amt', name: 'Env Amt', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'attack', name: 'Attack', min: 0.5, max: 5000, default: 5, skew: 0.3, unit: 'ms' },
        { id: 'decay', name: 'Decay', min: 1, max: 5000, default: 200, skew: 0.3, unit: 'ms' },
        { id: 'sustain', name: 'Sustain', min: 0, max: 100, default: 70, unit: '%' },
        { id: 'release', name: 'Release', min: 1, max: 10000, default: 300, skew: 0.3, unit: 'ms' },
        { id: 'volume', name: 'Volume', min: -60, max: 6, default: -6, unit: 'dB' },
        { id: 'glide', name: 'Glide', min: 0, max: 500, default: 0, skew: 0.4, unit: 'ms' },
      ],
      dspChain: [
        { type: 'oscillator', id: 'osc1', params: { waveform: 'saw', tune: '@tune', detune: '@detune' } },
        { type: 'ladder', id: 'filt1', params: { frequency: '@cutoff', resonance: '@resonance', env_amount: '@env_amt' } },
        { type: 'envelope_adsr', id: 'amp_env', params: { attack: '@attack', decay: '@decay', sustain: '@sustain', release: '@release' } },
        { type: 'gain', id: 'vol', params: { gain: '@volume' } },
      ],
      routing: { input: 'midi', chain: ['osc1', 'filt1', 'amp_env', 'vol'], output: 'stereo' },
    },
  },

  // ── 4. Multi-FX Rack ───────────────────────────────────────────────────
  {
    name: 'Multi-FX Rack',
    icon: 'fa-server',
    color: '#00e5a0',
    description: '5-section horizontal FX chain',
    pluginConfig: {
      name: 'FX Rack',
      width: 880,
      height: 320,
      bgColor: '#0a0f12',
      titleBarColor: '#141e24',
    },
    components: [
      { type: 'panel', x: 10, y: 10, width: 160, height: 300, bgColor: 'rgba(0,229,160,0.03)', borderColor: 'rgba(255,107,107,0.12)', borderRadius: 8, label: 'DRIVE' },
      { type: 'knob', x: 40, y: 45, width: 65, height: 75, color: '#ff6b6b', label: 'Drive' },
      { type: 'knob', x: 40, y: 140, width: 55, height: 65, color: '#ff6b6b', label: 'Drive Tone' },
      { type: 'panel', x: 180, y: 10, width: 160, height: 300, bgColor: 'rgba(0,229,160,0.03)', borderColor: 'rgba(255,215,0,0.12)', borderRadius: 8, label: 'CHORUS' },
      { type: 'knob', x: 210, y: 45, width: 65, height: 75, color: '#ffd700', label: 'Rate' },
      { type: 'knob', x: 210, y: 140, width: 55, height: 65, color: '#ffd700', label: 'Depth' },
      { type: 'panel', x: 350, y: 10, width: 160, height: 300, bgColor: 'rgba(0,229,160,0.03)', borderColor: 'rgba(0,200,255,0.12)', borderRadius: 8, label: 'DELAY' },
      { type: 'knob', x: 380, y: 45, width: 65, height: 75, color: '#00c8ff', label: 'Delay Time' },
      { type: 'knob', x: 380, y: 140, width: 55, height: 65, color: '#00c8ff', label: 'Delay FB' },
      { type: 'panel', x: 520, y: 10, width: 160, height: 300, bgColor: 'rgba(0,229,160,0.03)', borderColor: 'rgba(180,100,255,0.12)', borderRadius: 8, label: 'REVERB' },
      { type: 'knob', x: 550, y: 45, width: 65, height: 75, color: '#b464ff', label: 'Reverb Size' },
      { type: 'knob', x: 550, y: 140, width: 55, height: 65, color: '#b464ff', label: 'Reverb Damp' },
      { type: 'panel', x: 690, y: 10, width: 180, height: 300, bgColor: 'rgba(0,229,160,0.03)', borderColor: 'rgba(0,229,160,0.12)', borderRadius: 8, label: 'OUTPUT' },
      { type: 'knob', x: 730, y: 50, width: 70, height: 80, color: '#00e5a0', label: 'Master' },
      { type: 'meter', x: 720, y: 160, width: 24, height: 100, color: '#00e5a0', label: 'L' },
      { type: 'meter', x: 770, y: 160, width: 24, height: 100, color: '#00e5a0', label: 'R' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'FX Rack',
      parameters: [
        { id: 'drive', name: 'Drive', min: 0, max: 100, default: 30, unit: '%' },
        { id: 'drive_tone', name: 'Drive Tone', min: 200, max: 12000, default: 3000, skew: 0.25, unit: 'Hz' },
        { id: 'chorus_rate', name: 'Rate', min: 0.1, max: 10, default: 1.5, skew: 0.5, unit: 'Hz' },
        { id: 'chorus_depth', name: 'Depth', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'delay_time', name: 'Delay Time', min: 10, max: 1000, default: 250, skew: 0.4, unit: 'ms' },
        { id: 'delay_fb', name: 'Delay FB', min: 0, max: 95, default: 35, unit: '%' },
        { id: 'reverb_size', name: 'Reverb Size', min: 0, max: 100, default: 60, unit: '%' },
        { id: 'reverb_damp', name: 'Reverb Damp', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'master', name: 'Master', min: -60, max: 6, default: 0, unit: 'dB' },
      ],
      dspChain: [
        { type: 'overdrive', id: 'drive1', params: { drive: '@drive' } },
        { type: 'lowpass', id: 'drive_tone1', params: { frequency: '@drive_tone', q: 0.7 } },
        { type: 'chorus', id: 'chorus1', params: { rate: '@chorus_rate', depth: '@chorus_depth' } },
        { type: 'delay', id: 'delay1', params: { time: '@delay_time', feedback: '@delay_fb' } },
        { type: 'reverb', id: 'reverb1', params: { size: '@reverb_size', damping: '@reverb_damp' } },
        { type: 'gain', id: 'master1', params: { gain: '@master' } },
      ],
      routing: { input: 'stereo', chain: ['drive1', 'drive_tone1', 'chorus1', 'delay1', 'reverb1', 'master1'], output: 'stereo' },
    },
  },

  // ── 5. Lo-Fi Machine ───────────────────────────────────────────────────
  {
    name: 'Lo-Fi Machine',
    icon: 'fa-record-vinyl',
    color: '#c9a0dc',
    description: 'Bitcrusher + vinyl + wobble',
    pluginConfig: {
      name: 'Dusty Vibes',
      width: 450,
      height: 380,
      bgColor: '#1c1425',
      titleBarColor: '#2a1e38',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 420, height: 350, bgColor: 'rgba(201,160,220,0.03)', borderColor: 'rgba(201,160,220,0.1)', borderRadius: 14, label: '' },
      { type: 'label', x: 30, y: 25, width: 200, height: 26, label: 'DUSTY VIBES', color: '#c9a0dc', fontSize: 16 },
      { type: 'knob', x: 30, y: 70, width: 70, height: 80, color: '#c9a0dc', label: 'Bits' },
      { type: 'knob', x: 130, y: 70, width: 70, height: 80, color: '#c9a0dc', label: 'Sample Rate' },
      { type: 'knob', x: 250, y: 70, width: 70, height: 80, color: '#a07db8', label: 'Noise' },
      { type: 'knob', x: 350, y: 70, width: 70, height: 80, color: '#a07db8', label: 'Wobble' },
      { type: 'knob', x: 30, y: 190, width: 70, height: 80, color: '#8866a0', label: 'Hiss' },
      { type: 'knob', x: 130, y: 190, width: 70, height: 80, color: '#8866a0', label: 'Warmth' },
      { type: 'knob', x: 280, y: 200, width: 80, height: 90, color: '#dbb8f0', label: 'Mix' },
      { type: 'led', x: 400, y: 28, width: 12, height: 12, color: '#c9a0dc', label: '' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Dusty Vibes',
      parameters: [
        { id: 'bits', name: 'Bits', min: 2, max: 16, default: 12, unit: 'bit' },
        { id: 'sample_rate', name: 'Sample Rate', min: 1000, max: 44100, default: 22050, skew: 0.3, unit: 'Hz' },
        { id: 'noise', name: 'Noise', min: 0, max: 100, default: 15, unit: '%' },
        { id: 'wobble', name: 'Wobble', min: 0, max: 100, default: 30, unit: '%' },
        { id: 'hiss', name: 'Hiss', min: 0, max: 100, default: 10, unit: '%' },
        { id: 'warmth', name: 'Warmth', min: 0, max: 100, default: 40, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 80, unit: '%' },
      ],
      dspChain: [
        { type: 'bitcrusher', id: 'crush1', params: { bits: '@bits', sampleRate: '@sample_rate' } },
        { type: 'noise', id: 'vinyl_noise', params: { level: '@noise', type: 'pink' } },
        { type: 'lfo', id: 'wobble1', params: { rate: 0.3, depth: '@wobble', shape: 'sine' } },
        { type: 'noise', id: 'hiss1', params: { level: '@hiss', type: 'white' } },
        { type: 'saturation', id: 'warmth1', params: { drive: '@warmth', mix: 0.3 } },
        { type: 'lowpass', id: 'darken', params: { frequency: 8000, q: 0.5 } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['crush1', 'vinyl_noise', 'wobble1', 'hiss1', 'warmth1', 'darken', 'mix1'], output: 'stereo' },
    },
  },

  // ── 6. Plate Reverb ────────────────────────────────────────────────────
  {
    name: 'Plate Reverb',
    icon: 'fa-water',
    color: '#5cb3cc',
    description: 'Lush plate with shimmer',
    pluginConfig: {
      name: 'Crystal Plate',
      width: 500,
      height: 320,
      bgColor: '#0c1620',
      titleBarColor: '#142838',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 470, height: 290, bgColor: 'rgba(92,179,204,0.03)', borderColor: 'rgba(92,179,204,0.1)', backdropBlur: 8, borderRadius: 14, label: '' },
      { type: 'label', x: 30, y: 25, width: 200, height: 26, label: 'CRYSTAL PLATE', color: '#5cb3cc', fontSize: 16 },
      { type: 'knob', x: 30, y: 70, width: 75, height: 85, color: '#5cb3cc', label: 'Size' },
      { type: 'knob', x: 130, y: 70, width: 75, height: 85, color: '#5cb3cc', label: 'Decay' },
      { type: 'knob', x: 230, y: 70, width: 75, height: 85, color: '#4090aa', label: 'Damping' },
      { type: 'knob', x: 330, y: 70, width: 75, height: 85, color: '#4090aa', label: 'Pre-Delay' },
      { type: 'knob', x: 80, y: 195, width: 70, height: 80, color: '#78d0e8', label: 'Shimmer' },
      { type: 'knob', x: 200, y: 195, width: 70, height: 80, color: '#78d0e8', label: 'Width' },
      { type: 'knob', x: 340, y: 195, width: 80, height: 90, color: '#a0e0f0', label: 'Mix' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Crystal Plate',
      parameters: [
        { id: 'size', name: 'Size', min: 0, max: 100, default: 65, unit: '%' },
        { id: 'decay', name: 'Decay', min: 0.1, max: 30, default: 3.5, skew: 0.4, unit: 's' },
        { id: 'damping', name: 'Damping', min: 0, max: 100, default: 40, unit: '%' },
        { id: 'pre_delay', name: 'Pre-Delay', min: 0, max: 200, default: 20, unit: 'ms' },
        { id: 'shimmer', name: 'Shimmer', min: 0, max: 100, default: 25, unit: '%' },
        { id: 'width', name: 'Width', min: 0, max: 100, default: 80, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 30, unit: '%' },
      ],
      dspChain: [
        { type: 'delay', id: 'predelay', params: { time: '@pre_delay', feedback: 0 } },
        { type: 'reverb', id: 'plate1', params: { size: '@size', decay: '@decay', damping: '@damping' } },
        { type: 'shelf_high', id: 'shimmer1', params: { frequency: 4000, gain: '@shimmer' } },
        { type: 'pan', id: 'width1', params: { width: '@width' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['predelay', 'plate1', 'shimmer1', 'width1', 'mix1'], output: 'stereo' },
    },
  },

  // ── 7. Guitar Amp ──────────────────────────────────────────────────────
  {
    name: 'Guitar Amp',
    icon: 'fa-guitar',
    color: '#e8a838',
    description: 'Overdrive + EQ + spring reverb',
    pluginConfig: {
      name: 'Tube Growl',
      width: 600,
      height: 350,
      bgColor: '#1a1408',
      titleBarColor: '#2e2010',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 570, height: 320, bgColor: 'rgba(232,168,56,0.03)', borderColor: 'rgba(232,168,56,0.1)', borderRadius: 10, label: '' },
      { type: 'label', x: 30, y: 25, width: 200, height: 28, label: 'TUBE GROWL', color: '#e8a838', fontSize: 18 },
      { type: 'led', x: 540, y: 30, width: 14, height: 14, color: '#e8a838', label: '' },
      { type: 'knob', x: 30, y: 70, width: 75, height: 85, color: '#e8a838', label: 'Gain' },
      { type: 'knob', x: 130, y: 70, width: 65, height: 75, color: '#c88820', label: 'Bass' },
      { type: 'knob', x: 220, y: 70, width: 65, height: 75, color: '#c88820', label: 'Mid' },
      { type: 'knob', x: 310, y: 70, width: 65, height: 75, color: '#c88820', label: 'Treble' },
      { type: 'knob', x: 410, y: 70, width: 65, height: 75, color: '#c88820', label: 'Presence' },
      { type: 'knob', x: 500, y: 70, width: 75, height: 85, color: '#e8a838', label: 'Volume' },
      { type: 'knob', x: 80, y: 210, width: 65, height: 75, color: '#a87020', label: 'Reverb' },
      { type: 'button', x: 200, y: 230, width: 80, height: 30, color: '#e8a838', label: 'Bright' },
      { type: 'meter', x: 520, y: 200, width: 24, height: 100, color: '#e8a838', label: 'Out' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Tube Growl',
      parameters: [
        { id: 'gain', name: 'Gain', min: 0, max: 100, default: 55, unit: '%' },
        { id: 'bass', name: 'Bass', min: -15, max: 15, default: 2, unit: 'dB' },
        { id: 'mid', name: 'Mid', min: -15, max: 15, default: 4, unit: 'dB' },
        { id: 'treble', name: 'Treble', min: -15, max: 15, default: 3, unit: 'dB' },
        { id: 'presence', name: 'Presence', min: -15, max: 15, default: 2, unit: 'dB' },
        { id: 'volume', name: 'Volume', min: -60, max: 6, default: -6, unit: 'dB' },
        { id: 'reverb', name: 'Reverb', min: 0, max: 100, default: 20, unit: '%' },
      ],
      dspChain: [
        { type: 'waveshaper', id: 'preamp', params: { drive: '@gain', curve: 'tube' } },
        { type: 'shelf_low', id: 'bass1', params: { frequency: 250, gain: '@bass' } },
        { type: 'parametric_eq', id: 'mid1', params: { frequency: 800, gain: '@mid', q: 1.2 } },
        { type: 'shelf_high', id: 'treble1', params: { frequency: 3500, gain: '@treble' } },
        { type: 'shelf_high', id: 'presence1', params: { frequency: 5000, gain: '@presence' } },
        { type: 'reverb', id: 'spring1', params: { size: '@reverb', decay: 1.2, damping: 60 } },
        { type: 'gain', id: 'master', params: { gain: '@volume' } },
      ],
      routing: { input: 'mono', chain: ['preamp', 'bass1', 'mid1', 'treble1', 'presence1', 'spring1', 'master'], output: 'stereo' },
    },
  },

  // ── 8. Stereo Widener ──────────────────────────────────────────────────
  {
    name: 'Stereo Widener',
    icon: 'fa-arrows-left-right',
    color: '#66ddaa',
    description: 'Mid/side processing',
    pluginConfig: {
      name: 'Wide Open',
      width: 420,
      height: 300,
      bgColor: '#0a1a14',
      titleBarColor: '#142e22',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 390, height: 270, bgColor: 'rgba(102,221,170,0.03)', borderColor: 'rgba(102,221,170,0.1)', borderRadius: 12, label: '' },
      { type: 'label', x: 30, y: 25, width: 180, height: 26, label: 'WIDE OPEN', color: '#66ddaa', fontSize: 16 },
      { type: 'knob', x: 30, y: 70, width: 80, height: 90, color: '#66ddaa', label: 'Width' },
      { type: 'knob', x: 150, y: 70, width: 70, height: 80, color: '#44bb88', label: 'Mid Gain' },
      { type: 'knob', x: 260, y: 70, width: 70, height: 80, color: '#44bb88', label: 'Side Gain' },
      { type: 'knob', x: 40, y: 190, width: 65, height: 75, color: '#338866', label: 'Bass Mono' },
      { type: 'knob', x: 150, y: 190, width: 65, height: 75, color: '#338866', label: 'Side HP' },
      { type: 'meter', x: 290, y: 180, width: 24, height: 80, color: '#66ddaa', label: 'L' },
      { type: 'meter', x: 340, y: 180, width: 24, height: 80, color: '#66ddaa', label: 'R' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Wide Open',
      parameters: [
        { id: 'width', name: 'Width', min: 0, max: 200, default: 120, unit: '%' },
        { id: 'mid_gain', name: 'Mid Gain', min: -12, max: 12, default: 0, unit: 'dB' },
        { id: 'side_gain', name: 'Side Gain', min: -12, max: 12, default: 3, unit: 'dB' },
        { id: 'bass_mono', name: 'Bass Mono', min: 0, max: 500, default: 120, skew: 0.4, unit: 'Hz' },
        { id: 'side_hp', name: 'Side HP', min: 20, max: 2000, default: 200, skew: 0.3, unit: 'Hz' },
      ],
      dspChain: [
        { type: 'pan', id: 'width1', params: { width: '@width' } },
        { type: 'gain', id: 'mid1', params: { gain: '@mid_gain', channel: 'mid' } },
        { type: 'gain', id: 'side1', params: { gain: '@side_gain', channel: 'side' } },
        { type: 'highpass', id: 'side_hp1', params: { frequency: '@side_hp', q: 0.7 } },
        { type: 'lowpass', id: 'mono_below', params: { frequency: '@bass_mono', q: 0.7 } },
      ],
      routing: { input: 'stereo', chain: ['width1', 'mid1', 'side1', 'side_hp1', 'mono_below'], output: 'stereo' },
    },
  },

  // ── 9. Vocal Strip ─────────────────────────────────────────────────────
  {
    name: 'Vocal Strip',
    icon: 'fa-microphone',
    color: '#ff8866',
    description: 'EQ + comp + de-esser',
    pluginConfig: {
      name: 'Vox Chain',
      width: 550,
      height: 340,
      bgColor: '#18100c',
      titleBarColor: '#2e1c14',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 160, height: 310, bgColor: 'rgba(255,136,102,0.03)', borderColor: 'rgba(255,136,102,0.12)', borderRadius: 10, label: 'EQ' },
      { type: 'knob', x: 40, y: 45, width: 60, height: 70, color: '#ff8866', label: 'High Pass' },
      { type: 'knob', x: 40, y: 130, width: 60, height: 70, color: '#ff8866', label: 'Presence' },
      { type: 'knob', x: 40, y: 215, width: 60, height: 70, color: '#ff8866', label: 'Air' },
      { type: 'panel', x: 185, y: 15, width: 180, height: 310, bgColor: 'rgba(255,136,102,0.03)', borderColor: 'rgba(220,100,70,0.12)', borderRadius: 10, label: 'COMP' },
      { type: 'knob', x: 210, y: 45, width: 65, height: 75, color: '#dc6446', label: 'Threshold' },
      { type: 'knob', x: 290, y: 45, width: 55, height: 65, color: '#dc6446', label: 'Ratio' },
      { type: 'knob', x: 215, y: 150, width: 55, height: 65, color: '#b84830', label: 'Speed' },
      { type: 'meter', x: 315, y: 145, width: 20, height: 80, color: '#dc6446', label: 'GR' },
      { type: 'knob', x: 230, y: 240, width: 60, height: 70, color: '#dc6446', label: 'Makeup' },
      { type: 'panel', x: 375, y: 15, width: 160, height: 310, bgColor: 'rgba(255,136,102,0.03)', borderColor: 'rgba(255,170,100,0.12)', borderRadius: 10, label: 'DE-ESS' },
      { type: 'knob', x: 400, y: 50, width: 65, height: 75, color: '#ffaa64', label: 'De-Ess' },
      { type: 'knob', x: 400, y: 160, width: 55, height: 65, color: '#cc8844', label: 'Frequency' },
      { type: 'knob', x: 400, y: 250, width: 65, height: 75, color: '#ffaa64', label: 'Output' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Vox Chain',
      parameters: [
        { id: 'high_pass', name: 'High Pass', min: 20, max: 500, default: 80, skew: 0.3, unit: 'Hz' },
        { id: 'presence', name: 'Presence', min: -10, max: 10, default: 3, unit: 'dB' },
        { id: 'air', name: 'Air', min: -10, max: 10, default: 2, unit: 'dB' },
        { id: 'threshold', name: 'Threshold', min: -60, max: 0, default: -20, unit: 'dB' },
        { id: 'ratio', name: 'Ratio', min: 1, max: 20, default: 3, unit: ':1' },
        { id: 'speed', name: 'Speed', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'makeup', name: 'Makeup', min: 0, max: 24, default: 4, unit: 'dB' },
        { id: 'de_ess', name: 'De-Ess', min: 0, max: 100, default: 40, unit: '%' },
        { id: 'frequency', name: 'Frequency', min: 2000, max: 12000, default: 6000, skew: 0.3, unit: 'Hz' },
        { id: 'output', name: 'Output', min: -12, max: 12, default: 0, unit: 'dB' },
      ],
      dspChain: [
        { type: 'highpass', id: 'hp1', params: { frequency: '@high_pass', q: 0.7 } },
        { type: 'parametric_eq', id: 'pres1', params: { frequency: 3500, gain: '@presence', q: 1.5 } },
        { type: 'shelf_high', id: 'air1', params: { frequency: 10000, gain: '@air' } },
        { type: 'compressor', id: 'comp1', params: { threshold: '@threshold', ratio: '@ratio', attack: '@speed', release: '@speed', makeup: '@makeup' } },
        { type: 'compressor', id: 'deess1', params: { threshold: '@de_ess', ratio: 8, sidechain_freq: '@frequency' } },
        { type: 'gain', id: 'out1', params: { gain: '@output' } },
      ],
      routing: { input: 'mono', chain: ['hp1', 'pres1', 'air1', 'comp1', 'deess1', 'out1'], output: 'stereo' },
    },
  },

  // ── 10. Granular Pad ───────────────────────────────────────────────────
  {
    name: 'Granular Pad',
    icon: 'fa-cloud',
    color: '#9b7dd4',
    description: 'Granular texture synth',
    pluginConfig: {
      name: 'Grain Cloud',
      width: 560,
      height: 400,
      bgColor: '#120e1e',
      titleBarColor: '#201838',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 530, height: 370, bgColor: 'rgba(155,125,212,0.03)', borderColor: 'rgba(155,125,212,0.1)', borderRadius: 14, label: '' },
      { type: 'label', x: 30, y: 25, width: 200, height: 26, label: 'GRAIN CLOUD', color: '#9b7dd4', fontSize: 16 },
      { type: 'xy-pad', x: 30, y: 65, width: 180, height: 160, color: '#9b7dd4', label: 'Position / Size' },
      { type: 'knob', x: 240, y: 70, width: 65, height: 75, color: '#9b7dd4', label: 'Density' },
      { type: 'knob', x: 340, y: 70, width: 65, height: 75, color: '#9b7dd4', label: 'Scatter' },
      { type: 'knob', x: 440, y: 70, width: 65, height: 75, color: '#7b5db4', label: 'Pitch' },
      { type: 'knob', x: 240, y: 170, width: 65, height: 75, color: '#7b5db4', label: 'Freeze' },
      { type: 'knob', x: 340, y: 170, width: 65, height: 75, color: '#7b5db4', label: 'Texture' },
      { type: 'knob', x: 440, y: 170, width: 65, height: 75, color: '#5b3d94', label: 'Feedback' },
      { type: 'knob', x: 50, y: 270, width: 70, height: 80, color: '#b89de4', label: 'Reverb' },
      { type: 'knob', x: 170, y: 270, width: 70, height: 80, color: '#b89de4', label: 'Volume' },
      { type: 'knob', x: 340, y: 280, width: 80, height: 90, color: '#c8b0f0', label: 'Mix' },
    ],
    dspConfig: {
      pluginType: 'instrument',
      name: 'Grain Cloud',
      midi: { voices: 4, pitchBendRange: 12 },
      parameters: [
        { id: 'density', name: 'Density', min: 1, max: 100, default: 30, unit: 'grains' },
        { id: 'scatter', name: 'Scatter', min: 0, max: 100, default: 40, unit: '%' },
        { id: 'pitch', name: 'Pitch', min: -24, max: 24, default: 0, unit: 'st' },
        { id: 'freeze', name: 'Freeze', min: 0, max: 100, default: 0, unit: '%' },
        { id: 'texture', name: 'Texture', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'feedback', name: 'Feedback', min: 0, max: 95, default: 30, unit: '%' },
        { id: 'reverb', name: 'Reverb', min: 0, max: 100, default: 60, unit: '%' },
        { id: 'volume', name: 'Volume', min: -60, max: 6, default: -12, unit: 'dB' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 75, unit: '%' },
      ],
      dspChain: [
        { type: 'sample_player', id: 'grain1', params: { density: '@density', scatter: '@scatter', pitch: '@pitch', freeze: '@freeze' } },
        { type: 'lowpass', id: 'texture1', params: { frequency: '@texture', q: 0.8 } },
        { type: 'delay', id: 'fb1', params: { time: 150, feedback: '@feedback' } },
        { type: 'reverb', id: 'verb1', params: { size: '@reverb', decay: 4.0, damping: 40 } },
        { type: 'gain', id: 'vol1', params: { gain: '@volume' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'midi', chain: ['grain1', 'texture1', 'fb1', 'verb1', 'vol1', 'mix1'], output: 'stereo' },
    },
  },

  // ── 11. Eurorack Module ───────────────────────────────────────────────
  {
    name: 'Eurorack Module',
    icon: 'fa-microchip',
    color: '#8899aa',
    description: 'Dense vertical faceplate',
    pluginConfig: {
      name: 'Dual VCF',
      width: 220,
      height: 520,
      bgColor: '#1a1e24',
      titleBarColor: '#282e38',
    },
    components: [
      { type: 'panel', x: 5, y: 5, width: 210, height: 510, bgColor: 'rgba(136,153,170,0.03)', borderColor: 'rgba(136,153,170,0.15)', borderRadius: 4, label: '' },
      { type: 'label', x: 20, y: 10, width: 180, height: 20, label: 'DUAL VCF', color: '#8899aa', fontSize: 14 },
      { type: 'label', x: 20, y: 35, width: 80, height: 16, label: 'FILTER A', color: '#ff6b6b', fontSize: 10 },
      { type: 'knob', x: 20, y: 55, width: 55, height: 65, color: '#ff6b6b', label: 'Cutoff A', knobStyle: 'metallic' },
      { type: 'knob', x: 100, y: 55, width: 55, height: 65, color: '#ff6b6b', label: 'Res A', knobStyle: 'metallic' },
      { type: 'knob', x: 20, y: 130, width: 45, height: 55, color: '#cc5555', label: 'Env A', knobStyle: 'metallic' },
      { type: 'knob', x: 80, y: 130, width: 45, height: 55, color: '#cc5555', label: 'FM A', knobStyle: 'metallic' },
      { type: 'knob', x: 140, y: 130, width: 45, height: 55, color: '#cc5555', label: 'Drive A', knobStyle: 'metallic' },
      { type: 'label', x: 20, y: 200, width: 80, height: 16, label: 'FILTER B', color: '#4fc3f7', fontSize: 10 },
      { type: 'knob', x: 20, y: 220, width: 55, height: 65, color: '#4fc3f7', label: 'Cutoff B', knobStyle: 'metallic' },
      { type: 'knob', x: 100, y: 220, width: 55, height: 65, color: '#4fc3f7', label: 'Res B', knobStyle: 'metallic' },
      { type: 'knob', x: 20, y: 295, width: 45, height: 55, color: '#3090c0', label: 'Env B', knobStyle: 'metallic' },
      { type: 'knob', x: 80, y: 295, width: 45, height: 55, color: '#3090c0', label: 'FM B', knobStyle: 'metallic' },
      { type: 'knob', x: 140, y: 295, width: 45, height: 55, color: '#3090c0', label: 'Drive B', knobStyle: 'metallic' },
      { type: 'dropdown', x: 20, y: 365, width: 90, height: 24, color: '#8899aa', label: 'Mode' },
      { type: 'knob', x: 60, y: 400, width: 65, height: 75, color: '#8899aa', label: 'Mix', knobStyle: 'metallic' },
      { type: 'meter', x: 160, y: 380, width: 18, height: 80, color: '#ff6b6b', label: 'A' },
      { type: 'meter', x: 185, y: 380, width: 18, height: 80, color: '#4fc3f7', label: 'B' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Dual VCF',
      parameters: [
        { id: 'cutoff_a', name: 'Cutoff A', min: 20, max: 20000, default: 5000, skew: 0.25, unit: 'Hz' },
        { id: 'res_a', name: 'Res A', min: 0, max: 100, default: 30, unit: '%' },
        { id: 'env_a', name: 'Env A', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'fm_a', name: 'FM A', min: 0, max: 100, default: 0, unit: '%' },
        { id: 'drive_a', name: 'Drive A', min: 0, max: 100, default: 20, unit: '%' },
        { id: 'cutoff_b', name: 'Cutoff B', min: 20, max: 20000, default: 2000, skew: 0.25, unit: 'Hz' },
        { id: 'res_b', name: 'Res B', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'env_b', name: 'Env B', min: 0, max: 100, default: 30, unit: '%' },
        { id: 'fm_b', name: 'FM B', min: 0, max: 100, default: 0, unit: '%' },
        { id: 'drive_b', name: 'Drive B', min: 0, max: 100, default: 10, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 50, unit: '%' },
      ],
      dspChain: [
        { type: 'ladder', id: 'filt_a', params: { cutoff: '@cutoff_a', resonance: '@res_a', mode: 'LPF24' } },
        { type: 'saturation', id: 'drive_a1', params: { amount: '@drive_a' } },
        { type: 'bandpass', id: 'filt_b', params: { cutoff: '@cutoff_b', resonance: '@res_b' } },
        { type: 'saturation', id: 'drive_b1', params: { amount: '@drive_b' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['filt_a', 'drive_a1', 'filt_b', 'drive_b1', 'mix1'], output: 'stereo' },
    },
  },

  // ── 12. Pedal Stomp Box ─────────────────────────────────────────────
  {
    name: 'Pedal Stomp Box',
    icon: 'fa-shoe-prints',
    color: '#e8a838',
    description: 'Skeuomorphic guitar pedal',
    pluginConfig: {
      name: 'Fuzz Bomb',
      width: 280,
      height: 420,
      bgColor: '#8b4513',
      titleBarColor: '#6b3410',
    },
    components: [
      { type: 'panel', x: 10, y: 10, width: 260, height: 400, bgColor: 'rgba(232,168,56,0.04)', borderColor: 'rgba(232,168,56,0.2)', borderRadius: 20, label: '' },
      { type: 'label', x: 40, y: 20, width: 200, height: 30, label: 'FUZZ BOMB', color: '#ffd700', fontSize: 20 },
      { type: 'led', x: 130, y: 60, width: 16, height: 16, color: '#ff0000', label: '' },
      { type: 'knob', x: 30, y: 90, width: 70, height: 80, color: '#ffd700', label: 'Fuzz', knobStyle: 'vintage' },
      { type: 'knob', x: 130, y: 90, width: 70, height: 80, color: '#ffd700', label: 'Tone', knobStyle: 'vintage' },
      { type: 'knob', x: 80, y: 190, width: 80, height: 90, color: '#ffd700', label: 'Volume', knobStyle: 'vintage' },
      { type: 'knob', x: 30, y: 295, width: 55, height: 65, color: '#cc9900', label: 'Gate', knobStyle: 'vintage' },
      { type: 'knob', x: 130, y: 295, width: 55, height: 65, color: '#cc9900', label: 'Bias', knobStyle: 'vintage' },
      { type: 'button', x: 90, y: 370, width: 100, height: 30, color: '#c0c0c0', label: 'BYPASS', borderRadius: 15 },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Fuzz Bomb',
      parameters: [
        { id: 'fuzz', name: 'Fuzz', min: 0, max: 100, default: 70, unit: '%' },
        { id: 'tone', name: 'Tone', min: 200, max: 8000, default: 3000, skew: 0.3, unit: 'Hz' },
        { id: 'volume', name: 'Volume', min: -60, max: 6, default: -6, unit: 'dB' },
        { id: 'gate', name: 'Gate', min: -80, max: 0, default: -60, unit: 'dB' },
        { id: 'bias', name: 'Bias', min: 0, max: 100, default: 50, unit: '%' },
      ],
      dspChain: [
        { type: 'gate', id: 'gate1', params: { threshold: '@gate', ratio: 10, attack: 0.5, release: 50 } },
        { type: 'foldback', id: 'fuzz1', params: { threshold: '@fuzz' } },
        { type: 'lowpass', id: 'tone1', params: { cutoff: '@tone', resonance: 0.7 } },
        { type: 'gain', id: 'vol1', params: { gain_db: '@volume' } },
      ],
      routing: { input: 'mono', chain: ['gate1', 'fuzz1', 'tone1', 'vol1'], output: 'mono' },
    },
  },

  // ── 13. Console Channel Strip ───────────────────────────────────────
  {
    name: 'Channel Strip',
    icon: 'fa-sliders',
    color: '#7ec8e3',
    description: 'Vertical console strip',
    pluginConfig: {
      name: 'Console One',
      width: 180,
      height: 580,
      bgColor: '#141820',
      titleBarColor: '#1e2430',
    },
    components: [
      { type: 'panel', x: 5, y: 5, width: 170, height: 570, bgColor: 'rgba(126,200,227,0.02)', borderColor: 'rgba(126,200,227,0.1)', borderRadius: 6, label: '' },
      { type: 'label', x: 20, y: 10, width: 140, height: 18, label: 'CONSOLE ONE', color: '#7ec8e3', fontSize: 12 },
      { type: 'label', x: 20, y: 35, width: 60, height: 14, label: 'INPUT', color: '#aaa', fontSize: 9 },
      { type: 'knob', x: 15, y: 50, width: 50, height: 60, color: '#ff6b6b', label: 'Gain' },
      { type: 'knob', x: 85, y: 50, width: 50, height: 60, color: '#ff6b6b', label: 'HPF' },
      { type: 'label', x: 20, y: 120, width: 60, height: 14, label: 'EQ', color: '#aaa', fontSize: 9 },
      { type: 'knob', x: 15, y: 135, width: 45, height: 55, color: '#e8a838', label: 'High' },
      { type: 'knob', x: 85, y: 135, width: 45, height: 55, color: '#e8a838', label: 'High F' },
      { type: 'knob', x: 15, y: 200, width: 45, height: 55, color: '#4caf50', label: 'Mid' },
      { type: 'knob', x: 85, y: 200, width: 45, height: 55, color: '#4caf50', label: 'Mid F' },
      { type: 'knob', x: 50, y: 265, width: 45, height: 55, color: '#7b9cc9', label: 'Low' },
      { type: 'label', x: 20, y: 330, width: 60, height: 14, label: 'DYNAMICS', color: '#aaa', fontSize: 9 },
      { type: 'knob', x: 15, y: 345, width: 45, height: 55, color: '#b464ff', label: 'Comp' },
      { type: 'knob', x: 85, y: 345, width: 45, height: 55, color: '#b464ff', label: 'Speed' },
      { type: 'label', x: 20, y: 415, width: 60, height: 14, label: 'OUTPUT', color: '#aaa', fontSize: 9 },
      { type: 'slider', x: 40, y: 435, width: 30, height: 100, color: '#7ec8e3', label: 'Fader' },
      { type: 'knob', x: 95, y: 445, width: 45, height: 55, color: '#7ec8e3', label: 'Pan' },
      { type: 'meter', x: 140, y: 435, width: 16, height: 100, color: '#4caf50', label: '' },
      { type: 'button', x: 30, y: 545, width: 50, height: 22, color: '#ff6b6b', label: 'MUTE' },
      { type: 'button', x: 95, y: 545, width: 50, height: 22, color: '#4caf50', label: 'SOLO' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Console One',
      parameters: [
        { id: 'gain', name: 'Gain', min: -20, max: 20, default: 0, unit: 'dB' },
        { id: 'hpf', name: 'HPF', min: 20, max: 500, default: 60, skew: 0.3, unit: 'Hz' },
        { id: 'high', name: 'High', min: -15, max: 15, default: 0, unit: 'dB' },
        { id: 'high_f', name: 'High F', min: 2000, max: 16000, default: 8000, skew: 0.3, unit: 'Hz' },
        { id: 'mid', name: 'Mid', min: -15, max: 15, default: 0, unit: 'dB' },
        { id: 'mid_f', name: 'Mid F', min: 200, max: 8000, default: 1000, skew: 0.3, unit: 'Hz' },
        { id: 'low', name: 'Low', min: -15, max: 15, default: 0, unit: 'dB' },
        { id: 'comp', name: 'Comp', min: 0, max: 100, default: 30, unit: '%' },
        { id: 'speed', name: 'Speed', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'fader', name: 'Fader', min: -96, max: 12, default: 0, unit: 'dB' },
        { id: 'pan', name: 'Pan', min: -100, max: 100, default: 0, unit: '' },
      ],
      dspChain: [
        { type: 'gain', id: 'input_gain', params: { gain_db: '@gain' } },
        { type: 'highpass', id: 'hpf1', params: { frequency: '@hpf', q: 0.7 } },
        { type: 'shelf_high', id: 'eq_high', params: { frequency: '@high_f', gain: '@high' } },
        { type: 'parametric_eq', id: 'eq_mid', params: { frequency: '@mid_f', gain: '@mid', q: 1.5 } },
        { type: 'shelf_low', id: 'eq_low', params: { frequency: 200, gain: '@low' } },
        { type: 'compressor', id: 'comp1', params: { threshold: '@comp', ratio: 4, attack: '@speed', release: '@speed' } },
        { type: 'gain', id: 'fader1', params: { gain_db: '@fader' } },
        { type: 'pan', id: 'pan1', params: { pan: '@pan' } },
      ],
      routing: { input: 'mono', chain: ['input_gain', 'hpf1', 'eq_high', 'eq_mid', 'eq_low', 'comp1', 'fader1', 'pan1'], output: 'stereo' },
    },
  },

  // ── 14. DJ Mixer Channel ────────────────────────────────────────────
  {
    name: 'DJ Mixer',
    icon: 'fa-headphones',
    color: '#e040fb',
    description: 'DJ FX channel with XY pad',
    pluginConfig: {
      name: 'FX Deck',
      width: 360,
      height: 480,
      bgColor: '#0a0010',
      titleBarColor: '#180028',
    },
    components: [
      { type: 'panel', x: 10, y: 10, width: 340, height: 460, bgColor: 'rgba(224,64,251,0.03)', borderColor: 'rgba(224,64,251,0.12)', borderRadius: 12, label: '' },
      { type: 'label', x: 30, y: 15, width: 120, height: 22, label: 'FX DECK', color: '#e040fb', fontSize: 15 },
      { type: 'xy-pad', x: 30, y: 45, width: 180, height: 160, color: '#e040fb', label: 'Filter / Reverb' },
      { type: 'knob', x: 240, y: 50, width: 60, height: 70, color: '#e040fb', label: 'Echo', knobStyle: 'led-ring' },
      { type: 'knob', x: 240, y: 135, width: 60, height: 70, color: '#7c4dff', label: 'Feedback', knobStyle: 'led-ring' },
      { type: 'button', x: 235, y: 210, width: 70, height: 28, color: '#e040fb', label: 'FREEZE' },
      { type: 'knob', x: 30, y: 250, width: 55, height: 65, color: '#ff1744', label: 'Flanger', knobStyle: 'led-ring' },
      { type: 'knob', x: 110, y: 250, width: 55, height: 65, color: '#ffd600', label: 'Phaser', knobStyle: 'led-ring' },
      { type: 'knob', x: 190, y: 250, width: 55, height: 65, color: '#00e676', label: 'Gate', knobStyle: 'led-ring' },
      { type: 'knob', x: 270, y: 250, width: 55, height: 65, color: '#00b0ff', label: 'Crush', knobStyle: 'led-ring' },
      { type: 'slider', x: 50, y: 345, width: 30, height: 100, color: '#e040fb', label: 'Dry/Wet' },
      { type: 'meter', x: 120, y: 345, width: 20, height: 100, color: '#e040fb', label: 'L' },
      { type: 'meter', x: 150, y: 345, width: 20, height: 100, color: '#e040fb', label: 'R' },
      { type: 'knob', x: 220, y: 365, width: 70, height: 80, color: '#e040fb', label: 'Master', knobStyle: 'led-ring' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'FX Deck',
      parameters: [
        { id: 'echo', name: 'Echo', min: 10, max: 1000, default: 250, skew: 0.4, unit: 'ms' },
        { id: 'feedback', name: 'Feedback', min: 0, max: 95, default: 50, unit: '%' },
        { id: 'flanger', name: 'Flanger', min: 0, max: 100, default: 0, unit: '%' },
        { id: 'phaser', name: 'Phaser', min: 0, max: 100, default: 0, unit: '%' },
        { id: 'gate', name: 'Gate', min: -80, max: 0, default: -60, unit: 'dB' },
        { id: 'crush', name: 'Crush', min: 2, max: 16, default: 16, unit: 'bit' },
        { id: 'dry_wet', name: 'Dry/Wet', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'master', name: 'Master', min: -60, max: 6, default: 0, unit: 'dB' },
      ],
      dspChain: [
        { type: 'delay', id: 'echo1', params: { time: '@echo', feedback: '@feedback' } },
        { type: 'flanger', id: 'flanger1', params: { rate: 0.5, depth: '@flanger', feedback: 0.5 } },
        { type: 'phaser', id: 'phaser1', params: { rate: 0.4, depth: '@phaser', feedback: 0.6 } },
        { type: 'gate', id: 'gate1', params: { threshold: '@gate', ratio: 10, attack: 0.1, release: 20 } },
        { type: 'bitcrusher', id: 'crush1', params: { bit_depth: '@crush', rate_reduction: 1 } },
        { type: 'mix', id: 'drywet1', params: { ratio: '@dry_wet' } },
        { type: 'gain', id: 'master1', params: { gain_db: '@master' } },
      ],
      routing: { input: 'stereo', chain: ['echo1', 'flanger1', 'phaser1', 'gate1', 'crush1', 'drywet1', 'master1'], output: 'stereo' },
    },
  },

  // ── 15. Mastering Suite ─────────────────────────────────────────────
  {
    name: 'Mastering Suite',
    icon: 'fa-crown',
    color: '#ffd700',
    description: 'Wide horizontal mastering chain',
    pluginConfig: {
      name: 'Master Bus',
      width: 900,
      height: 340,
      bgColor: '#0e0e1a',
      titleBarColor: '#1a1a2e',
    },
    components: [
      { type: 'panel', x: 10, y: 10, width: 170, height: 320, bgColor: 'rgba(255,215,0,0.03)', borderColor: 'rgba(255,107,107,0.12)', borderRadius: 8, label: 'EQ' },
      { type: 'knob', x: 25, y: 40, width: 55, height: 65, color: '#ff6b6b', label: 'Low', knobStyle: 'metallic' },
      { type: 'knob', x: 100, y: 40, width: 55, height: 65, color: '#ff6b6b', label: 'Low F', knobStyle: 'metallic' },
      { type: 'knob', x: 25, y: 120, width: 55, height: 65, color: '#4caf50', label: 'Mid', knobStyle: 'metallic' },
      { type: 'knob', x: 100, y: 120, width: 55, height: 65, color: '#4caf50', label: 'Mid F', knobStyle: 'metallic' },
      { type: 'knob', x: 25, y: 200, width: 55, height: 65, color: '#4fc3f7', label: 'High', knobStyle: 'metallic' },
      { type: 'knob', x: 100, y: 200, width: 55, height: 65, color: '#4fc3f7', label: 'High F', knobStyle: 'metallic' },
      { type: 'panel', x: 190, y: 10, width: 170, height: 320, bgColor: 'rgba(255,215,0,0.03)', borderColor: 'rgba(180,100,255,0.12)', borderRadius: 8, label: 'COMP' },
      { type: 'knob', x: 210, y: 45, width: 60, height: 70, color: '#b464ff', label: 'Threshold', knobStyle: 'metallic' },
      { type: 'knob', x: 285, y: 45, width: 55, height: 65, color: '#b464ff', label: 'Ratio', knobStyle: 'metallic' },
      { type: 'knob', x: 210, y: 140, width: 55, height: 65, color: '#9040d0', label: 'Attack', knobStyle: 'metallic' },
      { type: 'knob', x: 285, y: 140, width: 55, height: 65, color: '#9040d0', label: 'Release', knobStyle: 'metallic' },
      { type: 'meter', x: 230, y: 225, width: 20, height: 80, color: '#b464ff', label: 'GR' },
      { type: 'panel', x: 370, y: 10, width: 160, height: 320, bgColor: 'rgba(255,215,0,0.03)', borderColor: 'rgba(255,170,0,0.12)', borderRadius: 8, label: 'STEREO' },
      { type: 'knob', x: 400, y: 50, width: 60, height: 70, color: '#ffaa00', label: 'Width', knobStyle: 'metallic' },
      { type: 'knob', x: 400, y: 145, width: 55, height: 65, color: '#cc8800', label: 'Mid Gain', knobStyle: 'metallic' },
      { type: 'knob', x: 400, y: 235, width: 55, height: 65, color: '#cc8800', label: 'Side Gain', knobStyle: 'metallic' },
      { type: 'panel', x: 540, y: 10, width: 170, height: 320, bgColor: 'rgba(255,215,0,0.03)', borderColor: 'rgba(0,229,160,0.12)', borderRadius: 8, label: 'LIMITER' },
      { type: 'knob', x: 575, y: 50, width: 70, height: 80, color: '#00e5a0', label: 'Ceiling', knobStyle: 'metallic' },
      { type: 'knob', x: 575, y: 155, width: 60, height: 70, color: '#00b080', label: 'Release', knobStyle: 'metallic' },
      { type: 'meter', x: 600, y: 240, width: 20, height: 70, color: '#00e5a0', label: 'GR' },
      { type: 'panel', x: 720, y: 10, width: 170, height: 320, bgColor: 'rgba(255,215,0,0.03)', borderColor: 'rgba(255,215,0,0.12)', borderRadius: 8, label: 'OUTPUT' },
      { type: 'knob', x: 760, y: 45, width: 75, height: 85, color: '#ffd700', label: 'Output', knobStyle: 'metallic' },
      { type: 'meter', x: 745, y: 160, width: 22, height: 120, color: '#ffd700', label: 'L' },
      { type: 'meter', x: 790, y: 160, width: 22, height: 120, color: '#ffd700', label: 'R' },
      { type: 'waveform', x: 830, y: 160, width: 40, height: 120, color: '#ffd700', label: '' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Master Bus',
      parameters: [
        { id: 'low', name: 'Low', min: -10, max: 10, default: 0, unit: 'dB' },
        { id: 'low_f', name: 'Low F', min: 40, max: 500, default: 120, skew: 0.3, unit: 'Hz' },
        { id: 'mid', name: 'Mid', min: -10, max: 10, default: 0, unit: 'dB' },
        { id: 'mid_f', name: 'Mid F', min: 200, max: 8000, default: 1500, skew: 0.3, unit: 'Hz' },
        { id: 'high', name: 'High', min: -10, max: 10, default: 0, unit: 'dB' },
        { id: 'high_f', name: 'High F', min: 2000, max: 16000, default: 8000, skew: 0.3, unit: 'Hz' },
        { id: 'threshold', name: 'Threshold', min: -40, max: 0, default: -12, unit: 'dB' },
        { id: 'ratio', name: 'Ratio', min: 1, max: 10, default: 2, unit: ':1' },
        { id: 'attack', name: 'Attack', min: 0.1, max: 100, default: 10, skew: 0.4, unit: 'ms' },
        { id: 'release', name: 'Release', min: 10, max: 500, default: 100, skew: 0.4, unit: 'ms' },
        { id: 'width', name: 'Width', min: 0, max: 200, default: 100, unit: '%' },
        { id: 'mid_gain', name: 'Mid Gain', min: -6, max: 6, default: 0, unit: 'dB' },
        { id: 'side_gain', name: 'Side Gain', min: -6, max: 6, default: 0, unit: 'dB' },
        { id: 'ceiling', name: 'Ceiling', min: -12, max: 0, default: -0.3, unit: 'dB' },
        { id: 'lim_release', name: 'Release', min: 1, max: 200, default: 50, skew: 0.4, unit: 'ms' },
        { id: 'output', name: 'Output', min: -12, max: 6, default: 0, unit: 'dB' },
      ],
      dspChain: [
        { type: 'shelf_low', id: 'eq_low', params: { frequency: '@low_f', gain: '@low' } },
        { type: 'parametric_eq', id: 'eq_mid', params: { frequency: '@mid_f', gain: '@mid', q: 1.0 } },
        { type: 'shelf_high', id: 'eq_high', params: { frequency: '@high_f', gain: '@high' } },
        { type: 'compressor', id: 'bus_comp', params: { threshold: '@threshold', ratio: '@ratio', attack: '@attack', release: '@release' } },
        { type: 'pan', id: 'stereo1', params: { width: '@width' } },
        { type: 'gain', id: 'mid_g', params: { gain_db: '@mid_gain', channel: 'mid' } },
        { type: 'gain', id: 'side_g', params: { gain_db: '@side_gain', channel: 'side' } },
        { type: 'limiter', id: 'limiter1', params: { threshold: '@ceiling', release: '@lim_release' } },
        { type: 'gain', id: 'output1', params: { gain_db: '@output' } },
      ],
      routing: { input: 'stereo', chain: ['eq_low', 'eq_mid', 'eq_high', 'bus_comp', 'stereo1', 'mid_g', 'side_g', 'limiter1', 'output1'], output: 'stereo' },
    },
  },
  // ── 808 Sub Synth (Wizardcore) ────────────────────────────────────────────
  {
    name: '808 Sub Synth',
    icon: 'fa-wave-square',
    color: '#9b59b6',
    description: 'Deep sub bass with pitch envelope - wizardcore style',
    pluginConfig: {
      name: 'Sub808',
      width: 560,
      height: 380,
      bgColor: '#1a0a1f',
      titleBarColor: '#2d1436',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 530, height: 350, bgColor: 'rgba(155,89,182,0.04)', borderColor: 'rgba(155,89,182,0.15)', borderRadius: 14, label: '' },
      { type: 'label', x: 30, y: 25, width: 200, height: 30, label: 'SUB 808', color: '#9b59b6', fontSize: 20 },
      { type: 'waveform', x: 250, y: 20, width: 280, height: 45, color: '#9b59b6', label: '' },
      { type: 'knob', x: 40, y: 85, width: 85, height: 95, color: '#9b59b6', label: 'Tune' },
      { type: 'knob', x: 150, y: 85, width: 85, height: 95, color: '#9b59b6', label: 'Pitch Env' },
      { type: 'knob', x: 260, y: 85, width: 85, height: 95, color: '#8e44ad', label: 'Decay' },
      { type: 'knob', x: 370, y: 85, width: 85, height: 95, color: '#8e44ad', label: 'Sustain' },
      { type: 'knob', x: 40, y: 220, width: 85, height: 95, color: '#a569bd', label: 'Drive' },
      { type: 'knob', x: 150, y: 220, width: 85, height: 95, color: '#a569bd', label: 'Sub' },
      { type: 'knob', x: 260, y: 220, width: 85, height: 95, color: '#a569bd', label: 'Click' },
      { type: 'knob', x: 370, y: 220, width: 85, height: 95, color: '#bb8fce', label: 'Output' },
      { type: 'led', x: 500, y: 30, width: 16, height: 16, color: '#9b59b6', label: '' },
    ],
    dspConfig: {
      pluginType: 'instrument',
      name: 'Sub808',
      parameters: [
        { id: 'tune', name: 'Tune', min: -24, max: 24, default: 0, unit: 'st' },
        { id: 'pitch_env', name: 'Pitch Env', min: 0, max: 100, default: 60, unit: '%' },
        { id: 'decay', name: 'Decay', min: 50, max: 3000, default: 800, skew: 0.4, unit: 'ms' },
        { id: 'sustain', name: 'Sustain', min: 0, max: 100, default: 20, unit: '%' },
        { id: 'drive', name: 'Drive', min: 0, max: 100, default: 15, unit: '%' },
        { id: 'sub', name: 'Sub', min: 0, max: 100, default: 80, unit: '%' },
        { id: 'click', name: 'Click', min: 0, max: 100, default: 25, unit: '%' },
        { id: 'output', name: 'Output', min: -24, max: 12, default: 0, unit: 'dB' },
      ],
      dspChain: [
        { type: 'sine_osc', id: 'sub_osc', params: { frequency: '@tune', level: '@sub' } },
        { type: 'pitch_envelope', id: 'pitch_env1', params: { amount: '@pitch_env', decay: 50 } },
        { type: 'adsr', id: 'amp_env', params: { attack: 1, decay: '@decay', sustain: '@sustain', release: 100 } },
        { type: 'click_generator', id: 'click1', params: { level: '@click', decay: 5 } },
        { type: 'saturation', id: 'drive1', params: { drive: '@drive', mix: 1.0 } },
        { type: 'gain', id: 'out1', params: { gain: '@output' } },
      ],
      routing: { input: 'midi', chain: ['sub_osc', 'pitch_env1', 'amp_env', 'click1', 'drive1', 'out1'], output: 'stereo' },
    },
  },

  // ── Lo-Fi Distortion ──────────────────────────────────────────────────────
  {
    name: 'Lo-Fi Distortion',
    icon: 'fa-radio',
    color: '#e67e22',
    description: 'Warm bitcrush and saturation',
    pluginConfig: {
      name: 'LoFi Crunch',
      width: 480,
      height: 320,
      bgColor: '#1f1408',
      titleBarColor: '#332210',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 450, height: 290, bgColor: 'rgba(230,126,34,0.04)', borderColor: 'rgba(230,126,34,0.12)', borderRadius: 12, label: '' },
      { type: 'label', x: 30, y: 25, width: 180, height: 28, label: 'LOFI CRUNCH', color: '#e67e22', fontSize: 18 },
      { type: 'knob', x: 40, y: 80, width: 80, height: 90, color: '#e67e22', label: 'Drive' },
      { type: 'knob', x: 145, y: 80, width: 80, height: 90, color: '#e67e22', label: 'Bits' },
      { type: 'knob', x: 250, y: 80, width: 80, height: 90, color: '#d35400', label: 'Sample Rate' },
      { type: 'knob', x: 355, y: 80, width: 80, height: 90, color: '#d35400', label: 'Tone' },
      { type: 'knob', x: 100, y: 200, width: 80, height: 90, color: '#f39c12', label: 'Noise' },
      { type: 'knob', x: 250, y: 200, width: 80, height: 90, color: '#f39c12', label: 'Mix' },
      { type: 'led', x: 420, y: 30, width: 14, height: 14, color: '#e67e22', label: '' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'LoFi Crunch',
      parameters: [
        { id: 'drive', name: 'Drive', min: 0, max: 100, default: 40, unit: '%' },
        { id: 'bits', name: 'Bits', min: 4, max: 16, default: 12, unit: 'bit' },
        { id: 'sample_rate', name: 'Sample Rate', min: 1000, max: 44100, default: 22050, skew: 0.3, unit: 'Hz' },
        { id: 'tone', name: 'Tone', min: 200, max: 12000, default: 6000, skew: 0.25, unit: 'Hz' },
        { id: 'noise', name: 'Noise', min: 0, max: 100, default: 10, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 100, unit: '%' },
      ],
      dspChain: [
        { type: 'saturation', id: 'drive1', params: { drive: '@drive', type: 'tape' } },
        { type: 'bitcrusher', id: 'crush1', params: { bits: '@bits', sampleRate: '@sample_rate' } },
        { type: 'lowpass', id: 'tone1', params: { frequency: '@tone', q: 0.7 } },
        { type: 'noise', id: 'noise1', params: { level: '@noise', type: 'vinyl' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['drive1', 'crush1', 'tone1', 'noise1', 'mix1'], output: 'stereo' },
    },
  },

  // ── Sidechain Compressor ──────────────────────────────────────────────────
  {
    name: 'Sidechain Compressor',
    icon: 'fa-compress',
    color: '#27ae60',
    description: 'Pumping sidechain compression',
    pluginConfig: {
      name: 'Pump SC',
      width: 540,
      height: 340,
      bgColor: '#0a1f12',
      titleBarColor: '#143d22',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 510, height: 310, bgColor: 'rgba(39,174,96,0.04)', borderColor: 'rgba(39,174,96,0.12)', borderRadius: 12, label: '' },
      { type: 'label', x: 30, y: 25, width: 180, height: 28, label: 'PUMP SC', color: '#27ae60', fontSize: 18 },
      { type: 'meter', x: 460, y: 60, width: 28, height: 180, color: '#27ae60', label: 'GR' },
      { type: 'knob', x: 40, y: 80, width: 80, height: 90, color: '#27ae60', label: 'Threshold' },
      { type: 'knob', x: 145, y: 80, width: 80, height: 90, color: '#27ae60', label: 'Ratio' },
      { type: 'knob', x: 250, y: 80, width: 80, height: 90, color: '#2ecc71', label: 'Attack' },
      { type: 'knob', x: 355, y: 80, width: 80, height: 90, color: '#2ecc71', label: 'Release' },
      { type: 'knob', x: 40, y: 210, width: 80, height: 90, color: '#58d68d', label: 'SC Freq' },
      { type: 'knob', x: 145, y: 210, width: 80, height: 90, color: '#58d68d', label: 'SC Mix' },
      { type: 'knob', x: 300, y: 210, width: 80, height: 90, color: '#58d68d', label: 'Mix' },
      { type: 'button', x: 400, y: 230, width: 80, height: 32, color: '#27ae60', label: 'SC Listen' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Pump SC',
      parameters: [
        { id: 'threshold', name: 'Threshold', min: -60, max: 0, default: -24, unit: 'dB' },
        { id: 'ratio', name: 'Ratio', min: 1, max: 20, default: 8, unit: ':1' },
        { id: 'attack', name: 'Attack', min: 0.1, max: 50, default: 0.5, skew: 0.4, unit: 'ms' },
        { id: 'release', name: 'Release', min: 10, max: 500, default: 150, skew: 0.4, unit: 'ms' },
        { id: 'sc_freq', name: 'SC Freq', min: 20, max: 500, default: 100, skew: 0.4, unit: 'Hz' },
        { id: 'sc_mix', name: 'SC Mix', min: 0, max: 100, default: 100, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 100, unit: '%' },
      ],
      dspChain: [
        { type: 'sidechain_input', id: 'sc_in', params: {} },
        { type: 'highpass', id: 'sc_filter', params: { frequency: '@sc_freq', q: 0.7 } },
        { type: 'compressor', id: 'comp1', params: { threshold: '@threshold', ratio: '@ratio', attack: '@attack', release: '@release', sidechain: 'sc_filter' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', sidechain: true, chain: ['sc_in', 'sc_filter', 'comp1', 'mix1'], output: 'stereo' },
    },
  },

  // ── Transient Shaper ──────────────────────────────────────────────────────
  {
    name: 'Transient Shaper',
    icon: 'fa-bolt',
    color: '#3498db',
    description: 'Attack and sustain control',
    pluginConfig: {
      name: 'Transient',
      width: 460,
      height: 300,
      bgColor: '#0a1520',
      titleBarColor: '#142535',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 430, height: 270, bgColor: 'rgba(52,152,219,0.04)', borderColor: 'rgba(52,152,219,0.12)', borderRadius: 12, label: '' },
      { type: 'label', x: 30, y: 25, width: 180, height: 28, label: 'TRANSIENT', color: '#3498db', fontSize: 18 },
      { type: 'waveform', x: 220, y: 20, width: 200, height: 40, color: '#3498db', label: '' },
      { type: 'knob', x: 50, y: 80, width: 90, height: 100, color: '#3498db', label: 'Attack' },
      { type: 'knob', x: 180, y: 80, width: 90, height: 100, color: '#2980b9', label: 'Sustain' },
      { type: 'knob', x: 310, y: 80, width: 90, height: 100, color: '#5dade2', label: 'Output' },
      { type: 'knob', x: 120, y: 195, width: 80, height: 90, color: '#85c1e9', label: 'Speed' },
      { type: 'knob', x: 250, y: 195, width: 80, height: 90, color: '#85c1e9', label: 'Mix' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Transient',
      parameters: [
        { id: 'attack', name: 'Attack', min: -100, max: 100, default: 0, unit: '%' },
        { id: 'sustain', name: 'Sustain', min: -100, max: 100, default: 0, unit: '%' },
        { id: 'output', name: 'Output', min: -24, max: 12, default: 0, unit: 'dB' },
        { id: 'speed', name: 'Speed', min: 0, max: 100, default: 50, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 100, unit: '%' },
      ],
      dspChain: [
        { type: 'envelope_follower', id: 'env1', params: { attack: 1, release: '@speed' } },
        { type: 'transient_shaper', id: 'trans1', params: { attack: '@attack', sustain: '@sustain' } },
        { type: 'gain', id: 'out1', params: { gain: '@output' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['env1', 'trans1', 'out1', 'mix1'], output: 'stereo' },
    },
  },

  // ── Reverb Tail ───────────────────────────────────────────────────────────
  {
    name: 'Reverb Tail',
    icon: 'fa-water',
    color: '#1abc9c',
    description: 'Lush algorithmic reverb',
    pluginConfig: {
      name: 'Tail Verb',
      width: 520,
      height: 340,
      bgColor: '#0a1a18',
      titleBarColor: '#143530',
    },
    components: [
      { type: 'panel', x: 15, y: 15, width: 490, height: 310, bgColor: 'rgba(26,188,156,0.04)', borderColor: 'rgba(26,188,156,0.12)', borderRadius: 12, label: '' },
      { type: 'label', x: 30, y: 25, width: 180, height: 28, label: 'TAIL VERB', color: '#1abc9c', fontSize: 18 },
      { type: 'waveform', x: 230, y: 20, width: 250, height: 40, color: '#1abc9c', label: '' },
      { type: 'knob', x: 40, y: 80, width: 80, height: 90, color: '#1abc9c', label: 'Size' },
      { type: 'knob', x: 145, y: 80, width: 80, height: 90, color: '#1abc9c', label: 'Decay' },
      { type: 'knob', x: 250, y: 80, width: 80, height: 90, color: '#16a085', label: 'Damping' },
      { type: 'knob', x: 355, y: 80, width: 80, height: 90, color: '#16a085', label: 'Pre-Delay' },
      { type: 'knob', x: 40, y: 210, width: 80, height: 90, color: '#48c9b0', label: 'Low Cut' },
      { type: 'knob', x: 145, y: 210, width: 80, height: 90, color: '#48c9b0', label: 'High Cut' },
      { type: 'knob', x: 250, y: 210, width: 80, height: 90, color: '#76d7c4', label: 'Width' },
      { type: 'knob', x: 355, y: 210, width: 80, height: 90, color: '#76d7c4', label: 'Mix' },
    ],
    dspConfig: {
      pluginType: 'effect',
      name: 'Tail Verb',
      parameters: [
        { id: 'size', name: 'Size', min: 0, max: 100, default: 60, unit: '%' },
        { id: 'decay', name: 'Decay', min: 0.1, max: 10, default: 2.5, skew: 0.4, unit: 's' },
        { id: 'damping', name: 'Damping', min: 0, max: 100, default: 40, unit: '%' },
        { id: 'predelay', name: 'Pre-Delay', min: 0, max: 200, default: 20, unit: 'ms' },
        { id: 'low_cut', name: 'Low Cut', min: 20, max: 500, default: 80, skew: 0.4, unit: 'Hz' },
        { id: 'high_cut', name: 'High Cut', min: 1000, max: 20000, default: 12000, skew: 0.25, unit: 'Hz' },
        { id: 'width', name: 'Width', min: 0, max: 100, default: 100, unit: '%' },
        { id: 'mix', name: 'Mix', min: 0, max: 100, default: 35, unit: '%' },
      ],
      dspChain: [
        { type: 'predelay', id: 'pre1', params: { time: '@predelay' } },
        { type: 'reverb', id: 'verb1', params: { size: '@size', decay: '@decay', damping: '@damping' } },
        { type: 'highpass', id: 'lc1', params: { frequency: '@low_cut', q: 0.7 } },
        { type: 'lowpass', id: 'hc1', params: { frequency: '@high_cut', q: 0.7 } },
        { type: 'pan', id: 'width1', params: { width: '@width' } },
        { type: 'mix', id: 'mix1', params: { ratio: '@mix' } },
      ],
      routing: { input: 'stereo', chain: ['pre1', 'verb1', 'lc1', 'hc1', 'width1', 'mix1'], output: 'stereo' },
    },
  },

];
